import React from "react";
import { actions } from "drugmaster_v_dbinder";
import { connect } from "react-redux";
import { NamespacesConsumer, translate } from "react-i18next";
import { withRouter } from "react-router-dom";
import { languageOptions, Permissions } from "../../utils";
import { LoggerContext } from "../../contexts";

import IDMPANEL from "idmpanel-pkg";
import Config from "../../config";
import cookie from "react-cookies";

import * as ALL from "../../components";
import * as ALLMCORE from "@material-ui/core";

import { Modal } from "qdm-component-library";

import {
  Paper,
  Grid,
  Typography,
  Button,
  Avatar,
  Divider,
  Link,
} from "@material-ui/core";

import qdmstyles from "./styles.json";
import "./index.css";
var aes256 = require("aes256");

class Drugmasterinstruction extends React.Component {
  static contextType = LoggerContext;
  constructor(props, context) {
    super(props, context);
    this.state = {
      permissionData: null,
    };
  }

  changeState = (key, value) => {
    this.setState({
      [key]: value,
    });
  };

  componentDidMount() {
    /// initializing transalation
    if (sessionStorage.defaultLng) {
      const { i18n } = this.props;
      i18n.changeLanguage(sessionStorage.defaultLng);
    }

    /// setlogger && dispatch of all events

    /// fetch all permission
  }

  ///fetching all permission

  shouldComponentUpdate(props, state) {
    return true;
  }

  render() {
    return (
      <NamespacesConsumer>
        {(t, { i18n }) => (
          <React.Fragment>
            <Paper
              key={"0"}
              id={"DlhyF"}
              elevation={"{3}"}
              style={qdmstyles.DlhyF}
            >
              <Grid
                key={"0"}
                id={"TgstR"}
                container={true}
                direction={"row"}
                justifyContent={"space-between"}
                alignItems={"center"}
                lg={"auto"}
                item={true}
                style={qdmstyles.BFHk}
              >
                <Grid
                  key={"0"}
                  id={"TgstR"}
                  container={""}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                  lg={"6"}
                  xs={"6"}
                  xl={"6"}
                  sm={"6"}
                  md={"6"}
                >
                  <Typography
                    key={"0"}
                    id={"instructions_header"}
                    align={"left"}
                    color={"initial"}
                    display={"initial"}
                    variant={"body1"}
                    children={"INSTRUCTIONS"}
                    aliasName={"instructionsheader"}
                    style={qdmstyles.NqY}
                  ></Typography>
                </Grid>
                <Grid
                  key={"1"}
                  id={"TgstR"}
                  container={""}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                >
                  <Button
                    key={"0"}
                    onClick={() => {
                      this.props.history.push("/instructionwindow");
                    }}
                    id={"instruction_add_new_button"}
                    variant={"text"}
                    color={"primary"}
                    children={"+ Add New"}
                    aliasName={"instructionaddnewbutton"}
                    style={qdmstyles.aRmAo}
                  ></Button>
                </Grid>
              </Grid>
              <Grid
                key={"1"}
                id={"6gUvB"}
                container={true}
                direction={"row"}
                justifyContent={"flex-start"}
                alignItems={"center"}
                item={true}
                lg={"12"}
                md={"12"}
                sm={"12"}
                xl={"12"}
                xs={"12"}
              >
                <Paper
                  key={"0"}
                  id={"1Cfv0"}
                  elevation={"{3}"}
                  style={qdmstyles.Cfv}
                >
                  <Grid
                    key={"0"}
                    id={"6gUvB"}
                    container={true}
                    direction={"row"}
                    justifyContent={"space-between"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    style={qdmstyles.REei}
                  >
                    <Grid
                      key={"0"}
                      id={"gP71K"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"4"}
                      md={"4"}
                      sm={"4"}
                      xs={"4"}
                      xl={"4"}
                    >
                      <Typography
                        key={"0"}
                        id={"practitioner_instruction_header"}
                        align={"left"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"PRACTITIONER INSTRUCTIONS"}
                        aliasName={"practitionerinstructionheader"}
                        style={qdmstyles.uaXK}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"gP71K"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-end"}
                      alignItems={"center"}
                      item={true}
                      lg={"2"}
                      md={"2"}
                      sm={"2"}
                      xs={"2"}
                      xl={"2"}
                    >
                      <Grid
                        key={"0"}
                        id={"Edit_icon2"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        item={true}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        aliasName={"editIcon1"}
                        style={qdmstyles.GUQ}
                      >
                        <Avatar
                          key={"0"}
                          id={"instrucrtion_delete_icon"}
                          alt={"Avatar"}
                          variant={"rounded"}
                          src={
                            "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317182133"
                          }
                          aliasName={"instrucrtiondeleteicon"}
                          style={qdmstyles.uOrk}
                        ></Avatar>
                        <Avatar
                          key={"1"}
                          onClick={() => {
                            this.props.history.push("/instructionwindow");
                          }}
                          id={"instruction_edit_icon"}
                          alt={"Avatar"}
                          variant={"rounded"}
                          src={
                            "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317313214"
                          }
                          aliasName={"instructionediticon"}
                          style={qdmstyles.IrCxA}
                        ></Avatar>
                      </Grid>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"3DIMg"}
                    container={true}
                    direction={"column"}
                    justifyContent={"flex-start"}
                    alignItems={"flex-start"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    style={qdmstyles.DIMg}
                  >
                    <Grid
                      key={"0"}
                      id={"roJ0A"}
                      container={true}
                      direction={"column"}
                      justifyContent={"flex-start"}
                      alignItems={"flex-start"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                    >
                      <Grid
                        key={"0"}
                        id={"kZfj1"}
                        container={true}
                        direction={"row"}
                        justifyContent={"space-between"}
                        alignItems={"center"}
                        lg={"12"}
                        md={"12"}
                        sm={"12"}
                        xl={"12"}
                        xs={"12"}
                        item={true}
                      >
                        <Grid
                          key={"0"}
                          id={"kZfj1"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"5"}
                          md={"5"}
                          sm={"5"}
                          xl={"5"}
                          xs={"5"}
                          style={qdmstyles.QVvGR}
                        >
                          <Typography
                            key={"0"}
                            id={"instruction_description_header"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Instruction Description"}
                            aliasName={"instructiondescriptionheader"}
                            style={qdmstyles.KYSzc}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"1"}
                          id={"kZfj1"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                          item={true}
                          style={qdmstyles.BwK}
                        >
                          <Divider
                            key={"0"}
                            id={"JxlSx"}
                            variant={"fullWidth"}
                            orientation={"horizontal"}
                            light={""}
                            flexItem={""}
                            absolute={""}
                          ></Divider>
                        </Grid>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"roJ0A"}
                        container={true}
                        direction={"column"}
                        justifyContent={"flex-start"}
                        alignItems={"flex-start"}
                        lg={"12"}
                        md={"12"}
                        sm={"12"}
                        xl={"12"}
                        xs={"12"}
                        style={qdmstyles.Alpzs}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={
                            "1. Pellentesque Tincidunt Tristique Neque, Eget Venenatis Enim Gravida Quis. Fusce At Egestas Libero. Cras Convallis Egestas Ullamcorper."
                          }
                          gutterBottom={""}
                          style={qdmstyles.bvMq}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"2"}
                        id={"pBxUS"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-start"}
                        alignItems={"center"}
                        lg={"12"}
                        md={"12"}
                        sm={"12"}
                        xl={"12"}
                        xs={"12"}
                        style={qdmstyles.pBxUS}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={
                            "2. Suspendisse Sed Ultricies Nisl, Pharetra Rutrum Mauris. Vestibulum At Massa Dui."
                          }
                          gutterBottom={""}
                          style={qdmstyles.kCP}
                        ></Typography>
                      </Grid>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"3DIMg"}
                    container={true}
                    direction={"column"}
                    justifyContent={"flex-start"}
                    alignItems={"flex-start"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    style={qdmstyles.KPApj}
                  >
                    <Grid
                      key={"0"}
                      id={"kZfj1"}
                      container={true}
                      direction={"row"}
                      justifyContent={"space-between"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      item={true}
                      style={qdmstyles.atD}
                    >
                      <Grid
                        key={"0"}
                        id={"kZfj1"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                      >
                        <Typography
                          key={"0"}
                          id={"instruction_local+language_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Instruction Local Language"}
                          aliasName={"instructionlocallanguageheader"}
                          style={qdmstyles.BmH}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"OWLPK"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-end"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        style={qdmstyles.OWLPK}
                      >
                        {/* See Less */}
                        <Link
                          key={"0"}
                          id={"iTnbM"}
                          underline={"always"}
                          comment={"See Less"}
                          color={"primary"}
                        >
                          <Typography
                            key={"0"}
                            id={"instruction_local_language_seeless_link"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"See Less"}
                            aliasName={
                              "instruction_local_language_seeless_button"
                            }
                            style={qdmstyles.KdNBr}
                          ></Typography>
                        </Link>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"kZfj1"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      item={true}
                      style={qdmstyles.XPRM}
                    >
                      <Divider
                        key={"0"}
                        id={"JxlSx"}
                        variant={"fullWidth"}
                        orientation={"horizontal"}
                        light={""}
                        flexItem={""}
                        absolute={""}
                      ></Divider>
                    </Grid>
                    <Grid
                      key={"2"}
                      id={"roJ0A"}
                      container={true}
                      direction={"column"}
                      justifyContent={"flex-start"}
                      alignItems={"flex-start"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                    >
                      <Grid
                        key={"0"}
                        id={"roJ0A"}
                        container={true}
                        direction={"column"}
                        justifyContent={"flex-start"}
                        alignItems={"flex-start"}
                        lg={"12"}
                        md={"12"}
                        sm={"12"}
                        xl={"12"}
                        xs={"12"}
                        style={qdmstyles.Hqwm}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"1. Fermentum Tristique"}
                          gutterBottom={""}
                          style={qdmstyles.HXTIa}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"JAGTO"}
                        container={true}
                        direction={"row"}
                        justifyContent={"space-between"}
                        alignItems={"center"}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"2. Quis Convallis"}
                          gutterBottom={""}
                          style={qdmstyles.Gz}
                        ></Typography>
                        <Grid
                          key={"1"}
                          id={"OWLPK"}
                          container={true}
                          direction={"row"}
                          justifyContent={"flex-end"}
                          alignItems={"center"}
                          lg={"5"}
                          md={"5"}
                          sm={"5"}
                          xl={"5"}
                          xs={"5"}
                          style={qdmstyles.EXFIP}
                        >
                          {/* See Less */}
                          <Link
                            key={"0"}
                            id={"iTnbM"}
                            underline={"always"}
                            comment={"See Less"}
                            color={"primary"}
                          >
                            <Typography
                              key={"0"}
                              id={"cTAwT"}
                              align={"inherit"}
                              color={"initial"}
                              display={"initial"}
                              variant={"body1"}
                              children={"See Less"}
                              style={qdmstyles.JGuE}
                            ></Typography>
                          </Link>
                        </Grid>
                      </Grid>
                    </Grid>
                  </Grid>
                </Paper>
              </Grid>
              <Grid
                key={"2"}
                id={"6gUvB"}
                container={true}
                direction={"row"}
                justifyContent={"flex-start"}
                alignItems={"center"}
                item={true}
                lg={"12"}
                md={"12"}
                sm={"12"}
                xl={"12"}
                xs={"12"}
              >
                <Paper
                  key={"0"}
                  id={"1Cfv0"}
                  elevation={"{3}"}
                  style={qdmstyles.DgPzP}
                >
                  <Grid
                    key={"0"}
                    id={"6gUvB"}
                    container={true}
                    direction={"row"}
                    justifyContent={"space-between"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    style={qdmstyles.StHh}
                  >
                    <Grid
                      key={"0"}
                      id={"gP71K"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"3"}
                      md={"3"}
                      sm={"3"}
                      xs={"3"}
                      xl={"3"}
                    >
                      <Typography
                        key={"0"}
                        id={"patient_instruction_header"}
                        align={"left"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"PATIENT INSTRUCTIONS"}
                        aliasName={"patientinstructionheader"}
                        style={qdmstyles.xNRLA}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"gP71K"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-end"}
                      alignItems={"center"}
                      item={true}
                      lg={"2"}
                      md={"2"}
                      sm={"2"}
                      xs={"2"}
                      xl={"2"}
                    >
                      <Grid
                        key={"0"}
                        id={"gP71K"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-end"}
                        alignItems={"center"}
                        item={true}
                        lg={true}
                        md={true}
                        sm={1}
                        xs={1}
                        xl={1}
                      >
                        <Grid
                          key={"0"}
                          id={"editicon_2"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"5"}
                          md={"3"}
                          sm={"3"}
                          xl={"3"}
                          xs={"3"}
                          aliasName={"editicon2"}
                          style={qdmstyles.VNps}
                        >
                          <Avatar
                            key={"0"}
                            id={"patient_instruction_delete_icon"}
                            alt={"Avatar"}
                            variant={"rounded"}
                            src={
                              "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317182133"
                            }
                            aliasName={"patientinstructiondeleteicon"}
                            style={qdmstyles.jbnc}
                          ></Avatar>
                          <Avatar
                            key={"1"}
                            id={"patient_instruction_edit_icon"}
                            alt={"Avatar"}
                            variant={"rounded"}
                            src={
                              "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317313214"
                            }
                            aliasName={"patientinstructionediticon"}
                            style={qdmstyles.AjcGc}
                          ></Avatar>
                        </Grid>
                      </Grid>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"3DIMg"}
                    container={true}
                    direction={"column"}
                    justifyContent={"flex-start"}
                    alignItems={"flex-start"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    style={qdmstyles.xZfC}
                  >
                    <Grid
                      key={"0"}
                      id={"roJ0A"}
                      container={true}
                      direction={"column"}
                      justifyContent={"flex-start"}
                      alignItems={"flex-start"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                    >
                      <Grid
                        key={"0"}
                        id={"kZfj1"}
                        container={true}
                        direction={"row"}
                        justifyContent={"space-between"}
                        alignItems={"center"}
                        lg={"12"}
                        md={"12"}
                        sm={"12"}
                        xl={"12"}
                        xs={"12"}
                        item={true}
                        style={qdmstyles.jqydl}
                      >
                        <Grid
                          key={"0"}
                          id={"kZfj1"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"5"}
                          md={"5"}
                          sm={"5"}
                          xl={"5"}
                          xs={"5"}
                        >
                          <Typography
                            key={"0"}
                            id={"cTAwT"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Instruction Description"}
                            style={qdmstyles.AQEkx}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"1"}
                          id={"kZfj1"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                          item={true}
                          style={qdmstyles.Ejr}
                        >
                          <Divider
                            key={"0"}
                            id={"JxlSx"}
                            variant={"fullWidth"}
                            orientation={"horizontal"}
                            light={""}
                            flexItem={""}
                            absolute={""}
                          ></Divider>
                        </Grid>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"roJ0A"}
                        container={true}
                        direction={"column"}
                        justifyContent={"flex-start"}
                        alignItems={"flex-start"}
                        style={qdmstyles.fkwZN}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={
                            "1. Pellentesque Tincidunt Tristique Neque, Eget Venenatis Enim Gravida Quis. Fusce At Egestas Libero. Cras Convallis Egestas Ullamcorper."
                          }
                          gutterBottom={""}
                          style={qdmstyles.tfrZh}
                        ></Typography>
                      </Grid>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"3DIMg"}
                    container={true}
                    direction={"column"}
                    justifyContent={"flex-start"}
                    alignItems={"flex-start"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    style={qdmstyles.ItCj}
                  >
                    <Grid
                      key={"0"}
                      id={"kZfj1"}
                      container={true}
                      direction={"row"}
                      justifyContent={"space-between"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      item={true}
                      style={qdmstyles.trIG}
                    >
                      <Grid
                        key={"0"}
                        id={"kZfj1"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Instruction Local Language"}
                          style={qdmstyles.pCeul}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"OWLPK"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-end"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        style={qdmstyles.mjHV}
                      >
                        {/* See Less */}
                        <Link
                          key={"0"}
                          id={"iTnbM"}
                          underline={"always"}
                          comment={"See Less"}
                          color={"primary"}
                        >
                          <Typography
                            key={"0"}
                            id={"cTAwT"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"See More"}
                            style={qdmstyles.sLBY}
                          ></Typography>
                        </Link>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"kZfj1"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      item={true}
                      style={qdmstyles.jLbz}
                    >
                      <Divider
                        key={"0"}
                        id={"JxlSx"}
                        variant={"fullWidth"}
                        orientation={"horizontal"}
                        light={""}
                        flexItem={""}
                        absolute={""}
                      ></Divider>
                    </Grid>
                  </Grid>
                </Paper>
              </Grid>
            </Paper>
          </React.Fragment>
        )}
      </NamespacesConsumer>
    );
  }
}
const mapStateToProps = (state) => ({});

export default connect(
  mapStateToProps,
  actions
)(withRouter(translate()(Drugmasterinstruction)));
