import React from "react";
import { actions } from "drugmaster_v_dbinder";
import { connect } from "react-redux";
import { NamespacesConsumer, translate } from "react-i18next";
import { withRouter } from "react-router-dom";
import { languageOptions, Permissions } from "../../utils";
import { LoggerContext } from "../../contexts";

import IDMPANEL from "idmpanel-pkg";
import Config from "../../config";
import cookie from "react-cookies";

import * as ALL from "../../components";
import * as ALLMCORE from "@material-ui/core";

import { Modal } from "qdm-component-library";

import {
  Grid,
  Paper,
  Typography,
  Avatar,
  Button,
  TextField,
} from "@material-ui/core";

import { Autocomplete } from "@material-ui/lab";

import qdmstyles from "./styles.json";
import "./index.css";
var aes256 = require("aes256");

class Test extends React.Component {
  static contextType = LoggerContext;
  constructor(props, context) {
    super(props, context);
    this.state = {
      permissionData: null,
    };
  }

  changeState = (key, value) => {
    this.setState({
      [key]: value,
    });
  };

  componentDidMount() {
    /// initializing transalation
    if (sessionStorage.defaultLng) {
      const { i18n } = this.props;
      i18n.changeLanguage(sessionStorage.defaultLng);
    }

    /// setlogger && dispatch of all events

    /// fetch all permission
  }

  ///fetching all permission

  shouldComponentUpdate(props, state) {
    return true;
  }

  render() {
    return (
      <NamespacesConsumer>
        {(t, { i18n }) => (
          <React.Fragment>
            <Grid
              key={"0"}
              id={"uo50z"}
              container={true}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
            >
              <Grid
                key={"0"}
                id={"FP3C7"}
                container={""}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                lg={"12"}
              >
                <Paper
                  key={"0"}
                  id={"bHiFf"}
                  elevation={"{3}"}
                  style={qdmstyles.bHiFf}
                >
                  <Grid
                    key={"0"}
                    id={"GYTKC"}
                    container={true}
                    direction={"row"}
                    justifyContent={"space-between"}
                    alignItems={"center"}
                    lg={"12"}
                    item={true}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    wrap={"wrap"}
                  >
                    <Grid
                      key={"0"}
                      id={"fQkr3"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-start"}
                      alignItems={"center"}
                      lg={"11"}
                      md={"11"}
                      sm={"11"}
                      xl={"11"}
                      xs={true}
                      item={true}
                      spacing={""}
                      style={qdmstyles.ybjm}
                    >
                      <Grid
                        key={"0"}
                        id={"Ut94g"}
                        container={true}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        item={true}
                        lg={1}
                        md={1}
                        sm={1}
                        xl={1}
                        xs={1}
                        wrap={"wrap"}
                        style={qdmstyles.hXVe}
                      >
                        <Grid
                          key={"0"}
                          id={"Po8nM"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"12"}
                          item={true}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                          wrap={"wrap"}
                          style={qdmstyles.kIwxI}
                        >
                          <Typography
                            key={"0"}
                            id={"serialnoTypography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={1}
                            noWrap={""}
                            aliasName={"serialnoTypography"}
                            style={qdmstyles.YXvH}
                          ></Typography>
                          <Paper
                            key={"1"}
                            id={"ejYaE"}
                            elevation={"{3}"}
                            style={qdmstyles.EceGx}
                          >
                            <Avatar
                              key={"0"}
                              id={"wg8M8"}
                              alt={"Avatar"}
                              variant={"rounded"}
                              src={
                                "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/325367543"
                              }
                              style={qdmstyles.wgM}
                            ></Avatar>
                          </Paper>
                        </Grid>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"CIdwA"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        spacing={""}
                        xs={"2"}
                        item={true}
                      >
                        <Typography
                          key={"0"}
                          id={"criteria_typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Criteria"}
                          aliasName={"criteriaheading"}
                          style={qdmstyles.NFcFY}
                        ></Typography>
                        <Typography
                          key={"1"}
                          id={"toDisplayTheValue_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"To display the value"}
                          aliasName={"toDisplayTheValueTypography"}
                          style={qdmstyles.RBdRy}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"2"}
                        id={"CIdwA"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={1}
                        md={1}
                        sm={1}
                        xl={1}
                        xs={1}
                      >
                        <Typography
                          key={"0"}
                          id={"defaultDispenseDuration&Uom_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Frequency"}
                          aliasName={"defaultDispenseDuration&Uomtypography"}
                          style={qdmstyles.HEqln}
                        ></Typography>
                        <Typography
                          key={"1"}
                          id={"TodisplayTheValue_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"TID - TWICE DAILY"}
                          aliasName={"TodisplayTheValueTypography"}
                          style={qdmstyles.hEiAp}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"3"}
                        id={"CIdwA"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                      >
                        <Typography
                          key={"0"}
                          id={"maxdispdurationval&Uom_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Duration Code & Uom"}
                          aliasName={"maxdispdurationval&UomTypography"}
                          style={qdmstyles.cINek}
                        ></Typography>
                        <Typography
                          key={"1"}
                          id={"toDisplayTheValue_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"02 DAYS"}
                          aliasName={"toDisplayTheValueTypography"}
                          style={qdmstyles.RNBG}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"4"}
                        id={"CIdwA"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                      >
                        <Typography
                          key={"0"}
                          id={"action_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Dose Value & Uom"}
                          aliasName={"actionTypography"}
                          style={qdmstyles.Hy}
                        ></Typography>
                        <Typography
                          key={"1"}
                          id={"gAydS"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"50 MG"}
                          aliasName={"stop"}
                          style={qdmstyles.cVTZN}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"5"}
                        id={"CIdwA"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                      >
                        <Typography
                          key={"0"}
                          id={"actionMessage_Id"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Infusion Rate & Uom"}
                          aliasName={"actionMessageId"}
                          style={qdmstyles.vKi}
                        ></Typography>
                        <Typography
                          key={"1"}
                          id={"toDisplayTheValue_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"5 ML"}
                          aliasName={"toDisplayTheValueTypography"}
                          style={qdmstyles.yPIYb}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"6"}
                        id={"CIdwA"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                      >
                        <Typography
                          key={"0"}
                          id={"actionMessage_Id"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Infuse Over Duration & Uom"}
                          aliasName={"actionMessageId"}
                          style={qdmstyles.LylQm}
                        ></Typography>
                        <Typography
                          key={"1"}
                          id={"toDisplayTheValue_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"5 ML"}
                          aliasName={"toDisplayTheValueTypography"}
                          style={qdmstyles.mwvTb}
                        ></Typography>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"vLpha"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={1}
                      md={1}
                      sm={1}
                      xl={1}
                      xs={1}
                    >
                      <Grid
                        key={"0"}
                        id={"drg92"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        item={true}
                        lg={"6"}
                        md={"6"}
                        sm={"6"}
                        xl={"6"}
                        xs={"6"}
                      >
                        <Avatar
                          key={"0"}
                          id={"ZCDUZ"}
                          alt={"Avatar"}
                          variant={"rounded"}
                          src={
                            "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317181412"
                          }
                          style={qdmstyles.LHJ}
                        ></Avatar>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"w7zVn"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        item={true}
                        lg={"6"}
                        md={"6"}
                        sm={"6"}
                        xl={"6"}
                        xs={"6"}
                      >
                        <Avatar
                          key={"0"}
                          id={"SzaNP"}
                          alt={"Avatar"}
                          variant={"rounded"}
                          src={
                            "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317182133"
                          }
                          style={qdmstyles.JIM}
                        ></Avatar>
                      </Grid>
                    </Grid>
                  </Grid>
                </Paper>
              </Grid>
            </Grid>
            <Paper
              key={"1"}
              id={"TOgaz"}
              elevation={"{3}"}
              style={qdmstyles.ifEi}
            >
              <Grid
                key={"0"}
                id={"TgstR"}
                container={true}
                direction={"row"}
                justifyContent={"space-between"}
                alignItems={"center"}
                lg={"12"}
                md={"12"}
                sm={"12"}
                xl={"12"}
                xs={"12"}
                style={qdmstyles.nZwf}
              >
                <Grid
                  key={"0"}
                  id={"TgstR"}
                  container={""}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                  lg={"6"}
                >
                  <Typography
                    key={"0"}
                    id={"compoundHeading_Typography"}
                    align={"left"}
                    color={"initial"}
                    display={"initial"}
                    variant={"body1"}
                    children={"COMPOUND"}
                    aliasName={"compoundHeading"}
                    style={qdmstyles.XYee}
                  ></Typography>
                </Grid>
                <Grid
                  key={"1"}
                  id={"TgstR"}
                  container={""}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                >
                  <Button
                    key={"0"}
                    id={"CompondAddnewButton_button"}
                    variant={"text"}
                    color={"primary"}
                    children={"+Add New"}
                    aliasName={"CompondAddnewButton"}
                    style={qdmstyles.qxqzq}
                  ></Button>
                </Grid>
              </Grid>
              <Grid
                key={"1"}
                id={"oZ25m"}
                container={true}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                spacing={"3"}
              >
                <Grid
                  key={"0"}
                  id={"R3123"}
                  container={true}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  lg={"2"}
                  md={"2"}
                  item={true}
                  sm={"6"}
                  xl={"2"}
                  xs={"6"}
                >
                  <Grid
                    key={"0"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Typography
                      key={"0"}
                      id={"DrugcodeHeading_Typography"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Drug Code"}
                      aliasName={"DrugcodeHeading"}
                      style={qdmstyles.oOWWg}
                    ></Typography>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    style={qdmstyles.VWah}
                  >
                    <Autocomplete
                      id={"KrQku"}
                      style={qdmstyles?.KrQku}
                      value={this.state?.test_krqku ?? null}
                      onLoad={() =>
                        this.setState({
                          test_krqku: this.state?.test_krqku ?? null,
                        })
                      }
                      getOptionLabel={(option) => option?.["label"]}
                      options={[] ?? []}
                      size={"small"}
                      renderInput={(params) => (
                        <ALLMCORE.TextField
                          {...params}
                          label={"label"}
                          variant="outlined"
                        />
                      )}
                    />
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Autocomplete
                      id={"66WPR"}
                      style={qdmstyles?.WPR}
                      value={this.state?.test_66wpr ?? null}
                      onLoad={() =>
                        this.setState({
                          test_66wpr: this.state?.test_66wpr ?? null,
                        })
                      }
                      getOptionLabel={(option) => option?.["label"]}
                      options={[] ?? []}
                      size={"small"}
                      renderInput={(params) => (
                        <ALLMCORE.TextField
                          {...params}
                          label={"label"}
                          variant="outlined"
                        />
                      )}
                    />
                  </Grid>
                </Grid>
                <Grid
                  key={"1"}
                  id={"nL5qY"}
                  container={true}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                  lg={"2"}
                  md={"2"}
                  sm={"6"}
                  xl={"2"}
                  xs={"6"}
                  spacing={""}
                >
                  <Grid
                    key={"0"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Typography
                      key={"0"}
                      id={"descriptionHeading_Typography"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Description"}
                      aliasName={"descriptionHeading"}
                      style={qdmstyles.BQby}
                    ></Typography>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <TextField
                      key={"0"}
                      id={"p4SrD"}
                      label={""}
                      placeholder={"Local language"}
                      type={"text"}
                      variant={"outlined"}
                      size={"small"}
                      fullWidth={true}
                      style={qdmstyles.AmexN}
                    ></TextField>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <TextField
                      key={"0"}
                      id={"p4SrD"}
                      label={""}
                      placeholder={"Tallman"}
                      type={"text"}
                      variant={"outlined"}
                      size={"small"}
                      fullWidth={true}
                      style={qdmstyles.WKQKM}
                    ></TextField>
                  </Grid>
                </Grid>
                <Grid
                  key={"2"}
                  id={"nL5qY"}
                  container={true}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                  lg={"2"}
                  md={"2"}
                  sm={"4"}
                  xl={"2"}
                  xs={"4"}
                  spacing={""}
                >
                  <Grid
                    key={"0"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Typography
                      key={"0"}
                      id={"strengthandconcentrationHeading_Typography"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Strength/Concentration"}
                      aliasName={"strengthandconcentrationHeading"}
                      style={qdmstyles.vMVl}
                    ></Typography>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <TextField
                      key={"0"}
                      id={"p4SrD"}
                      label={""}
                      placeholder={""}
                      type={"text"}
                      variant={"outlined"}
                      size={"small"}
                      style={qdmstyles.DiNy}
                    ></TextField>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <TextField
                      key={"0"}
                      id={"p4SrD"}
                      label={""}
                      placeholder={""}
                      type={"text"}
                      variant={"outlined"}
                      size={"small"}
                      style={qdmstyles.bxze}
                    ></TextField>
                  </Grid>
                </Grid>
                <Grid
                  key={"3"}
                  id={"nL5qY"}
                  container={true}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                  lg={"2"}
                  md={"2"}
                  sm={"3"}
                  xl={"2"}
                  xs={"3"}
                  spacing={""}
                >
                  <Grid
                    key={"0"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Typography
                      key={"0"}
                      id={"RequiredQuantityHeading_Typography"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Required Quantity & UOM"}
                      aliasName={"RequiredQuantityHeading"}
                      style={qdmstyles.bwyF}
                    ></Typography>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"oZV3U"}
                    container={true}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"CTVXT"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"6"}
                      md={"6"}
                      sm={"6"}
                      xl={"6"}
                      xs={"6"}
                    >
                      <TextField
                        key={"0"}
                        id={"p4SrD"}
                        label={""}
                        placeholder={""}
                        type={"text"}
                        variant={"outlined"}
                        size={"small"}
                        style={qdmstyles.ntw}
                      ></TextField>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"CTVXT"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"6"}
                      md={"6"}
                      sm={"6"}
                      xl={"6"}
                      xs={"6"}
                    >
                      <Autocomplete
                        id={"RXKeF"}
                        style={qdmstyles?.RXKeF}
                        value={this.state?.test_rxkef ?? null}
                        onLoad={() =>
                          this.setState({
                            test_rxkef: this.state?.test_rxkef ?? null,
                          })
                        }
                        getOptionLabel={(option) => option?.["label"]}
                        options={[] ?? []}
                        size={"small"}
                        renderInput={(params) => (
                          <ALLMCORE.TextField
                            {...params}
                            label={"label"}
                            variant="outlined"
                          />
                        )}
                      />
                    </Grid>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"oZV3U"}
                    container={true}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"CTVXT"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"6"}
                      md={"6"}
                      sm={"6"}
                      xl={"6"}
                      xs={"6"}
                    >
                      <TextField
                        key={"0"}
                        id={"p4SrD"}
                        label={""}
                        placeholder={""}
                        type={"text"}
                        variant={"outlined"}
                        size={"small"}
                        style={qdmstyles.aALc}
                      ></TextField>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"CTVXT"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"6"}
                      md={"6"}
                      sm={"6"}
                      xl={"6"}
                      xs={"6"}
                    >
                      <Autocomplete
                        id={"vCCTN"}
                        style={qdmstyles?.vCCTN}
                        value={this.state?.test_vcctn ?? null}
                        onLoad={() =>
                          this.setState({
                            test_vcctn: this.state?.test_vcctn ?? null,
                          })
                        }
                        getOptionLabel={(option) => option?.["label"]}
                        options={[] ?? []}
                        size={"small"}
                        renderInput={(params) => (
                          <ALLMCORE.TextField
                            {...params}
                            label={"label"}
                            variant="outlined"
                          />
                        )}
                      />
                    </Grid>
                  </Grid>
                </Grid>
                <Grid
                  key={"4"}
                  id={"nL5qY"}
                  container={true}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                  lg={"4"}
                  md={"4"}
                  sm={"6"}
                  xl={"4"}
                  xs={"6"}
                  spacing={""}
                  style={qdmstyles.JmE}
                >
                  <Grid
                    key={"0"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Typography
                      key={"0"}
                      id={"remarksHeading_Typography"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Remarks"}
                      aliasName={"RemarksHeading"}
                      style={qdmstyles.uhqNl}
                    ></Typography>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    style={qdmstyles.qATo}
                  >
                    <TextField
                      key={"0"}
                      id={"p4SrD"}
                      label={""}
                      placeholder={"Type Here"}
                      type={"text"}
                      variant={"outlined"}
                      select={""}
                      fullWidth={true}
                      size={"small"}
                      style={qdmstyles.kuQrT}
                    ></TextField>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"CTVXT"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"12"}
                    xl={"12"}
                    md={"12"}
                    sm={"12"}
                    xs={"12"}
                  >
                    <TextField
                      key={"0"}
                      id={"p4SrD"}
                      label={""}
                      placeholder={"Type Here"}
                      type={"text"}
                      variant={"outlined"}
                      select={""}
                      fullWidth={true}
                      size={"small"}
                      style={qdmstyles.ED}
                    ></TextField>
                  </Grid>
                </Grid>
              </Grid>
            </Paper>
          </React.Fragment>
        )}
      </NamespacesConsumer>
    );
  }
}
const mapStateToProps = (state) => ({});

export default connect(mapStateToProps, actions)(withRouter(translate()(Test)));
