import React from "react";
import { actions } from "drugmaster_v_dbinder";
import { NamespacesConsumer, translate } from "react-i18next";
import { withRouter } from "react-router-dom";
import { languageOptions, Permissions } from "../../utils";
import { LoggerContext } from "../../contexts";
import IDMPANEL from "idmpanel-pkg";
import { useDispatch, useSelector } from "react-redux";
import Config from "../../config";
import * as ALLMCORE from "@material-ui/core";
import cookie from "react-cookies";

import * as ALL from "../../components";
import { Modal } from "qdm-component-library";
import {
  Grid,
  Divider,
  Typography,
  Paper,
  Button,
  TextField,
  Avatar,
} from "@material-ui/core";

import { Autocomplete } from "@material-ui/lab";
import qdmstyles from "./styles.json";
import "./index.css";
var aes256 = require("aes256");

function Orderdetailscomp(props) {
  const dispatch = useDispatch();

  const contextType = React.useContext(LoggerContext);
  const [state, setState] = React.useState({
    permissionData: null,
  });

  const changeState = (key, value) => {
    setState({
      ...state,
      [key]: value,
    });
  };

  React.useEffect(() => {
    /// initializing transalation
    if (sessionStorage.defaultLng) {
      const { i18n } = props;
      i18n.changeLanguage(sessionStorage.defaultLng);
    }
    /// setlogger && dispatch of all events

    /// fetch all permission
  }, []);

  ///fetching all permission

  React.useEffect(() => {}, [state]);

  const { data, index } = props;

  return (
    <NamespacesConsumer>
      {(t, { i18n }) => (
        <React.Fragment>
          <Grid
            key={"0"}
            id={"DIAYz"}
            container={true}
            direction={"row"}
            justifyContent={"center"}
            alignItems={"flex-start"}
            item={true}
            lg={"12"}
            md={"12"}
            sm={"12"}
            xl={"12"}
            xs={"12"}
          >
            <Grid
              key={"0"}
              id={"n1RM4"}
              container={""}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
              lg={"12"}
            >
              <Divider
                key={"0"}
                id={"yohAt"}
                variant={"fullWidth"}
                flexItem={""}
                orientation={"horizontal"}
                light={true}
              ></Divider>
            </Grid>
            <Grid
              key={"1"}
              id={"CZVZN"}
              container={true}
              direction={"row"}
              justifyContent={"flex-start"}
              alignItems={"center"}
              lg={"12"}
              item={true}
              md={"12"}
              sm={"12"}
              spacing={1}
              xl={"12"}
              xs={"12"}
              style={qdmstyles.vFYR}
            >
              <Grid
                key={"0"}
                id={"2MXs9"}
                container={true}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                item={true}
                lg={"3"}
                md={"3"}
                sm={"3"}
                xl={"3"}
                xs={"3"}
                style={qdmstyles.ixFX}
              >
                <Grid
                  key={"0"}
                  id={"d2nWC"}
                  container={""}
                  direction={"column"}
                  justifyContent={"flex-start"}
                  alignItems={"center"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.LLDye}
                >
                  <Typography
                    key={"0"}
                    id={"routesAllowedHeading_typogrpahy"}
                    align={"inherit"}
                    color={"initial"}
                    display={"initial"}
                    variant={"body1"}
                    children={"Routes Allowed"}
                    aliasName={"routesAllowedHeading"}
                    style={qdmstyles.oJhzE}
                  ></Typography>
                </Grid>
                <Grid
                  key={"1"}
                  id={"d2nWC"}
                  container={""}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                >
                  <Autocomplete
                    id={"XhCxn"}
                    style={qdmstyles?.XhCxn}
                    value={state?.orderdetailscomp_xhcxn ?? null}
                    onLoad={() =>
                      setState({
                        orderdetailscomp_xhcxn:
                          state?.orderdetailscomp_xhcxn ?? null,
                      })
                    }
                    getOptionLabel={(option) => option?.["label"]}
                    options={[] ?? []}
                    size={"small"}
                    renderInput={(params) => (
                      <ALLMCORE.TextField
                        {...params}
                        label={"label"}
                        variant="outlined"
                      />
                    )}
                  />
                </Grid>
              </Grid>
              <Grid
                key={"1"}
                id={"2MXs9"}
                container={true}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                item={true}
                lg={"3"}
                sm={"3"}
                md={"3"}
                xl={"3"}
                xs={"3"}
              >
                <Grid
                  key={"0"}
                  id={"d2nWC"}
                  container={""}
                  direction={"column"}
                  justifyContent={"flex-start"}
                  alignItems={"center"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.UY}
                >
                  <Typography
                    key={"0"}
                    id={"defaultRouteHeading_Typography"}
                    align={"inherit"}
                    color={"initial"}
                    display={"initial"}
                    variant={"body1"}
                    children={"Default Route"}
                    aliasName={"defaultRouteHeading"}
                    style={qdmstyles.PoAZ}
                  ></Typography>
                </Grid>
                <Grid
                  key={"1"}
                  id={"d2nWC"}
                  container={""}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                >
                  <Autocomplete
                    id={"i43fB"}
                    style={qdmstyles?.ifB}
                    value={state?.orderdetailscomp_i43fb ?? null}
                    onLoad={() =>
                      setState({
                        orderdetailscomp_i43fb:
                          state?.orderdetailscomp_i43fb ?? null,
                      })
                    }
                    getOptionLabel={(option) => option?.["label"]}
                    options={[] ?? []}
                    size={"small"}
                    renderInput={(params) => (
                      <ALLMCORE.TextField
                        {...params}
                        label={"label"}
                        variant="outlined"
                      />
                    )}
                  />
                </Grid>
              </Grid>
            </Grid>
            <Grid
              key={"2"}
              id={"n1RM4"}
              container={""}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
              lg={"12"}
            >
              <Divider
                key={"0"}
                id={"yohAt"}
                variant={"fullWidth"}
                flexItem={""}
                orientation={"horizontal"}
                light={true}
              ></Divider>
            </Grid>
            <Grid
              key={"3"}
              id={"b7AAp"}
              container={true}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
              item={true}
              lg={"12"}
              md={"12"}
              sm={"12"}
              xl={"12"}
              xs={"12"}
            >
              <Grid
                key={"0"}
                id={"pULoO"}
                container={true}
                direction={"row"}
                justifyContent={"flex-start"}
                alignItems={"flex-start"}
                lg={"auto"}
                item={true}
                alignContent={"stretch"}
                md={"auto"}
                sm={"auto"}
                xl={"auto"}
                xs={"auto"}
                style={qdmstyles.xHdJK}
              >
                <Typography
                  key={"0"}
                  id={"addNewFrequencyHeading_typography"}
                  align={"inherit"}
                  color={"primary"}
                  display={"initial"}
                  variant={"body1"}
                  children={"ADD NEW FREQUENCY DEFAULTS"}
                  aliasName={"addNewFrequencyHeading"}
                  style={qdmstyles.JzD}
                ></Typography>
              </Grid>
              <Grid
                key={"1"}
                id={"0NqD2"}
                container={true}
                direction={"row"}
                justifyContent={"flex-start"}
                alignItems={"center"}
                item={true}
                lg={"12"}
                style={qdmstyles.RptnI}
              >
                <Paper
                  key={"0"}
                  id={"A4OWh"}
                  elevation={""}
                  variant={"elevation"}
                  style={qdmstyles.szBGC}
                >
                  <Grid
                    key={"0"}
                    id={"0wzSg"}
                    container={true}
                    direction={"row"}
                    justifyContent={"flex-start"}
                    alignItems={"center"}
                    style={qdmstyles.jQG}
                  >
                    <Grid
                      key={"0"}
                      id={"AySG3"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-start"}
                      alignItems={"center"}
                      item={true}
                      style={qdmstyles.wbZg}
                    >
                      <Typography
                        key={"0"}
                        id={
                          "definecriteriabypateintandPharamacyHeading_Typography"
                        }
                        align={"inherit"}
                        color={"primary"}
                        display={"initial"}
                        variant={"body1"}
                        children={"DEFINE CRITERIA BY PATIENT AND PHARMACY"}
                        aliasName={"definecriteriabypateintandPharamacyHeading"}
                        style={qdmstyles.usJu}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"h6VuZ"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-start"}
                      alignItems={"center"}
                      lg={"12"}
                      item={""}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.CBPgO}
                    >
                      <Grid
                        key={"0"}
                        id={"wDQNk"}
                        container={""}
                        direction={"row"}
                        justifyContent={"flex-start"}
                        alignItems={"center"}
                        item={true}
                        lg={"auto"}
                        style={qdmstyles.JUvC}
                      >
                        <Button
                          key={"0"}
                          id={"addNewRuleSetButton_button"}
                          variant={"text"}
                          color={"primary"}
                          children={"Add New Rule Set"}
                          aliasName={"addNewRuleSetButton"}
                          style={qdmstyles.uoSZ}
                        ></Button>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"CU1k8"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                      >
                        <Typography
                          key={"0"}
                          id={"OrHeading_Typography"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"(or)"}
                          aliasName={"OrHeading"}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"2"}
                        id={"DWbgk"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        item={true}
                        lg={"auto"}
                        style={qdmstyles.VzQap}
                      >
                        <Button
                          key={"0"}
                          id={"addExistingRuleSetButton_Button"}
                          variant={"text"}
                          color={"primary"}
                          children={"Add Existing Rule Set"}
                          aliasName={"addExistingRuleSetButton"}
                          style={qdmstyles.ViHd}
                        ></Button>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"2"}
                      id={"6nXk1"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      style={qdmstyles.kjKZp}
                    >
                      <Divider
                        key={"0"}
                        id={"aL6n6"}
                        variant={"fullWidth"}
                        orientation={"horizontal"}
                        light={""}
                        flexItem={""}
                        absolute={""}
                      ></Divider>
                    </Grid>
                    <Grid
                      key={"3"}
                      id={"C2Q2C"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-start"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.zMYKr}
                    >
                      <Grid
                        key={"0"}
                        id={"A0aTF"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-start"}
                        alignItems={"center"}
                        lg={"12"}
                        md={"12"}
                        sm={"12"}
                        xl={"12"}
                        xs={"12"}
                      >
                        <Grid
                          key={"0"}
                          id={"K8jKe"}
                          container={true}
                          direction={"row"}
                          justifyContent={"flex-start"}
                          alignItems={"flex-start"}
                          lg={"10"}
                          spacing={"2"}
                          md={"10"}
                          sm={"10"}
                          xl={"10"}
                          xs={"10"}
                        >
                          <Grid
                            key={"0"}
                            id={"MwW3q"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            lg={"4"}
                            item={true}
                            md={"6"}
                            sm={"6"}
                            xl={"4"}
                            xs={"6"}
                            style={qdmstyles.TcBm}
                          >
                            <Typography
                              key={"0"}
                              id={"TI1yl"}
                              align={"inherit"}
                              color={"initial"}
                              display={"initial"}
                              variant={"body1"}
                              children={"Frequency"}
                              style={qdmstyles.NvVfV}
                            ></Typography>
                            <Autocomplete
                              id={"r9IiL"}
                              style={qdmstyles?.rIiL}
                              value={state?.orderdetailscomp_r9iil ?? null}
                              onLoad={() =>
                                setState({
                                  orderdetailscomp_r9iil:
                                    state?.orderdetailscomp_r9iil ?? null,
                                })
                              }
                              getOptionLabel={(option) => option?.["label"]}
                              options={[] ?? []}
                              renderInput={(params) => (
                                <ALLMCORE.TextField
                                  {...params}
                                  label={"label"}
                                  variant="outlined"
                                />
                              )}
                            />
                          </Grid>
                          <Grid
                            key={"1"}
                            id={"XcWnj"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            lg={"2"}
                            item={true}
                            md={"3"}
                            sm={"3"}
                            xl={"2"}
                            xs={"3"}
                          >
                            <Typography
                              key={"0"}
                              id={"b6j0B"}
                              align={"inherit"}
                              color={"initial"}
                              display={"initial"}
                              variant={"body1"}
                              children={"Duration Code & Uom"}
                              style={qdmstyles.OZUK}
                            ></Typography>
                            <Grid
                              key={"1"}
                              id={"mTFOI"}
                              container={true}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"12"}
                              md={"12"}
                              sm={"12"}
                              xl={"12"}
                              xs={"12"}
                              style={qdmstyles.jYGK}
                            >
                              <Grid
                                key={"0"}
                                id={"56Ktj"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"5"}
                                md={"5"}
                                sm={"5"}
                                xl={"5"}
                                xs={"5"}
                                item={true}
                                style={qdmstyles.JGib}
                              >
                                <TextField
                                  key={"0"}
                                  id={"KOrzv"}
                                  label={""}
                                  placeholder={""}
                                  type={"text"}
                                  variant={"outlined"}
                                  fullWidth={true}
                                  margin={"dense"}
                                ></TextField>
                              </Grid>
                              <Divider
                                key={"1"}
                                id={"i68WA"}
                                variant={"fullWidth"}
                                flexItem={true}
                                orientation={"vertical"}
                                style={qdmstyles.qFJy}
                              ></Divider>
                              <Grid
                                key={"2"}
                                id={"VtLuv"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"5"}
                                md={"5"}
                                sm={"5"}
                                xl={"5"}
                                xs={"5"}
                                item={true}
                              >
                                <Autocomplete
                                  id={"4hHRU"}
                                  style={qdmstyles?.hHRU}
                                  value={state?.orderdetailscomp_4hhru ?? null}
                                  onLoad={() =>
                                    setState({
                                      orderdetailscomp_4hhru:
                                        state?.orderdetailscomp_4hhru ?? null,
                                    })
                                  }
                                  getOptionLabel={(option) => option?.["label"]}
                                  options={[] ?? []}
                                  renderInput={(params) => (
                                    <ALLMCORE.TextField
                                      {...params}
                                      label={"label"}
                                      variant="outlined"
                                    />
                                  )}
                                />
                              </Grid>
                            </Grid>
                          </Grid>
                          <Grid
                            key={"2"}
                            id={"XcWnj"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            lg={"2"}
                            item={true}
                            md={"3"}
                            sm={"3"}
                            xl={"2"}
                            xs={"3"}
                          >
                            <Typography
                              key={"0"}
                              id={"b6j0B"}
                              align={"inherit"}
                              color={"initial"}
                              display={"initial"}
                              variant={"body1"}
                              children={"Dose Value & Uom"}
                              style={qdmstyles.ir}
                            ></Typography>
                            <Grid
                              key={"1"}
                              id={"mTFOI"}
                              container={true}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"12"}
                              md={"12"}
                              sm={"12"}
                              xl={"12"}
                              xs={"12"}
                              style={qdmstyles.piT}
                            >
                              <Grid
                                key={"0"}
                                id={"56Ktj"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"5"}
                                md={"5"}
                                sm={"5"}
                                xl={"5"}
                                xs={"5"}
                                item={true}
                                style={qdmstyles.PO}
                              >
                                <TextField
                                  key={"0"}
                                  id={"KOrzv"}
                                  label={""}
                                  placeholder={""}
                                  type={"text"}
                                  variant={"outlined"}
                                  fullWidth={true}
                                  margin={"dense"}
                                ></TextField>
                              </Grid>
                              <Divider
                                key={"1"}
                                id={"i68WA"}
                                variant={"fullWidth"}
                                flexItem={true}
                                orientation={"vertical"}
                                style={qdmstyles.mp}
                              ></Divider>
                              <Grid
                                key={"2"}
                                id={"VtLuv"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"5"}
                                md={"5"}
                                sm={"5"}
                                xl={"5"}
                                xs={"5"}
                                item={true}
                              >
                                <Autocomplete
                                  id={"N4cBF"}
                                  style={qdmstyles?.NcBF}
                                  value={state?.orderdetailscomp_n4cbf ?? null}
                                  onLoad={() =>
                                    setState({
                                      orderdetailscomp_n4cbf:
                                        state?.orderdetailscomp_n4cbf ?? null,
                                    })
                                  }
                                  getOptionLabel={(option) => option?.["label"]}
                                  options={[] ?? []}
                                  renderInput={(params) => (
                                    <ALLMCORE.TextField
                                      {...params}
                                      label={"label"}
                                      variant="outlined"
                                    />
                                  )}
                                />
                              </Grid>
                            </Grid>
                          </Grid>
                          <Grid
                            key={"3"}
                            id={"XcWnj"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            lg={"2"}
                            item={true}
                            md={"6"}
                            sm={"6"}
                            xl={"2"}
                            xs={"6"}
                          >
                            <Typography
                              key={"0"}
                              id={"b6j0B"}
                              align={"inherit"}
                              color={"initial"}
                              display={"initial"}
                              variant={"body1"}
                              children={"Infusion Rate & Uom"}
                              style={qdmstyles.HGhh}
                            ></Typography>
                            <Grid
                              key={"1"}
                              id={"mTFOI"}
                              container={true}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"12"}
                              md={"12"}
                              sm={"12"}
                              xl={"12"}
                              xs={"12"}
                              style={qdmstyles.lJmR}
                            >
                              <Grid
                                key={"0"}
                                id={"56Ktj"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"5"}
                                md={"5"}
                                sm={"5"}
                                xl={"5"}
                                xs={"5"}
                                item={true}
                                style={qdmstyles.yfdK}
                              >
                                <TextField
                                  key={"0"}
                                  id={"KOrzv"}
                                  label={""}
                                  placeholder={""}
                                  type={"text"}
                                  variant={"outlined"}
                                  fullWidth={true}
                                  margin={"dense"}
                                ></TextField>
                              </Grid>
                              <Divider
                                key={"1"}
                                id={"i68WA"}
                                variant={"fullWidth"}
                                flexItem={true}
                                orientation={"vertical"}
                                style={qdmstyles.QKY}
                              ></Divider>
                              <Grid
                                key={"2"}
                                id={"VtLuv"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"5"}
                                md={"5"}
                                sm={"5"}
                                xl={"5"}
                                xs={"5"}
                                item={true}
                              >
                                <Autocomplete
                                  id={"dbedu"}
                                  style={qdmstyles?.dbedu}
                                  value={state?.orderdetailscomp_dbedu ?? null}
                                  onLoad={() =>
                                    setState({
                                      orderdetailscomp_dbedu:
                                        state?.orderdetailscomp_dbedu ?? null,
                                    })
                                  }
                                  getOptionLabel={(option) => option?.["label"]}
                                  options={[] ?? []}
                                  renderInput={(params) => (
                                    <ALLMCORE.TextField
                                      {...params}
                                      label={"label"}
                                      variant="outlined"
                                    />
                                  )}
                                />
                              </Grid>
                            </Grid>
                          </Grid>
                          <Grid
                            key={"4"}
                            id={"XcWnj"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            lg={"2"}
                            item={true}
                            md={"6"}
                            sm={"6"}
                            xl={"2"}
                            xs={"6"}
                          >
                            <Typography
                              key={"0"}
                              id={"b6j0B"}
                              align={"inherit"}
                              color={"initial"}
                              display={"initial"}
                              variant={"body1"}
                              children={"Infuse Over Duration & Uom"}
                              style={qdmstyles.kGTbK}
                            ></Typography>
                            <Grid
                              key={"1"}
                              id={"mTFOI"}
                              container={true}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"12"}
                              md={"12"}
                              sm={"12"}
                              xl={"12"}
                              xs={"12"}
                              style={qdmstyles.MkFF}
                            >
                              <Grid
                                key={"0"}
                                id={"56Ktj"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"5"}
                                md={"5"}
                                sm={"5"}
                                xl={"5"}
                                xs={"5"}
                                item={true}
                                style={qdmstyles.yFOl}
                              >
                                <TextField
                                  key={"0"}
                                  id={"KOrzv"}
                                  label={""}
                                  placeholder={""}
                                  type={"text"}
                                  variant={"outlined"}
                                  fullWidth={true}
                                  margin={"dense"}
                                ></TextField>
                              </Grid>
                              <Divider
                                key={"1"}
                                id={"i68WA"}
                                variant={"fullWidth"}
                                flexItem={true}
                                orientation={"vertical"}
                                style={qdmstyles.EODfM}
                              ></Divider>
                              <Grid
                                key={"2"}
                                id={"VtLuv"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"5"}
                                md={"5"}
                                sm={"5"}
                                xl={"5"}
                                xs={"5"}
                                item={true}
                              >
                                <Autocomplete
                                  id={"Ase2R"}
                                  style={qdmstyles?.AseR}
                                  value={state?.orderdetailscomp_ase2r ?? null}
                                  onLoad={() =>
                                    setState({
                                      orderdetailscomp_ase2r:
                                        state?.orderdetailscomp_ase2r ?? null,
                                    })
                                  }
                                  getOptionLabel={(option) => option?.["label"]}
                                  options={[] ?? []}
                                  renderInput={(params) => (
                                    <ALLMCORE.TextField
                                      {...params}
                                      label={"label"}
                                      variant="outlined"
                                    />
                                  )}
                                />
                              </Grid>
                            </Grid>
                          </Grid>
                        </Grid>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"4"}
                      id={"iRF0G"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-end"}
                      alignItems={"center"}
                      item={true}
                      style={qdmstyles.UVxYh}
                    >
                      <Grid
                        key={"0"}
                        id={"Bf7YT"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"4"}
                        item={true}
                        style={qdmstyles.RfC}
                      >
                        <Button
                          key={"0"}
                          id={"MoXx0"}
                          variant={"text"}
                          color={"primary"}
                          children={"Save & Add another"}
                          style={qdmstyles.dLEbQ}
                        ></Button>
                        <Button
                          key={"1"}
                          id={"MoXx0"}
                          variant={"contained"}
                          color={"primary"}
                          children={" Add"}
                          size={"small"}
                          style={qdmstyles.ihHC}
                        ></Button>
                      </Grid>
                    </Grid>
                  </Grid>
                </Paper>
              </Grid>
            </Grid>
            <Grid
              key={"4"}
              id={"ncT2W"}
              container={true}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
            >
              <Grid
                key={"0"}
                id={"TZfNs"}
                container={""}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                item={true}
                lg={"12"}
                md={"12"}
                sm={"12"}
                xl={"12"}
                xs={"12"}
              >
                <Paper
                  key={"0"}
                  id={"bx6t7"}
                  elevation={"{3}"}
                  style={qdmstyles.bxt}
                >
                  <Grid
                    key={"0"}
                    id={"BTGwG"}
                    container={true}
                    direction={"row"}
                    justifyContent={"space-between"}
                    alignItems={"center"}
                    style={qdmstyles.BTGwG}
                  >
                    <Grid
                      key={"0"}
                      id={"mCpCY"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"4"}
                      item={true}
                    >
                      <Typography
                        key={"0"}
                        id={"1LrwM"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"frequency defaults"}
                        style={qdmstyles.LrwM}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"Xtuss"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"4"}
                      item={true}
                      style={qdmstyles.Xtuss}
                    >
                      <Button
                        key={"0"}
                        id={"T8AoZ"}
                        variant={"text"}
                        color={"primary"}
                        children={"+ Add new"}
                        style={qdmstyles.TAoZ}
                      ></Button>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"uo50z"}
                    container={true}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                  >
                    <Grid
                      key={"0"}
                      id={"FP3C7"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                    >
                      <Paper
                        key={"0"}
                        id={"bHiFf"}
                        elevation={"{3}"}
                        style={qdmstyles.uzpZ}
                      >
                        <Grid
                          key={"0"}
                          id={"GYTKC"}
                          container={true}
                          direction={"row"}
                          justifyContent={"space-between"}
                          alignItems={"center"}
                          lg={"12"}
                          item={true}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                          wrap={"wrap"}
                        >
                          <Grid
                            key={"0"}
                            id={"fQkr3"}
                            container={true}
                            direction={"row"}
                            justifyContent={"flex-start"}
                            alignItems={"center"}
                            lg={"11"}
                            md={"11"}
                            sm={"11"}
                            xl={"11"}
                            xs={true}
                            item={true}
                            spacing={""}
                            style={qdmstyles.cMI}
                          >
                            <Grid
                              key={"0"}
                              id={"Ut94g"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              item={true}
                              lg={1}
                              md={1}
                              sm={1}
                              xl={1}
                              xs={1}
                              wrap={"wrap"}
                              style={qdmstyles.BHnWT}
                            >
                              <Grid
                                key={"0"}
                                id={"Po8nM"}
                                container={""}
                                direction={"row"}
                                justifyContent={"center"}
                                alignItems={"center"}
                                lg={"12"}
                                item={true}
                                md={"12"}
                                sm={"12"}
                                xl={"12"}
                                xs={"12"}
                                wrap={"wrap"}
                                style={qdmstyles.ReVMC}
                              >
                                <Typography
                                  key={"0"}
                                  id={"serialnoTypography"}
                                  align={"inherit"}
                                  color={"initial"}
                                  display={"initial"}
                                  variant={"body1"}
                                  children={1}
                                  noWrap={""}
                                  aliasName={"serialnoTypography"}
                                  style={qdmstyles.CbFTC}
                                ></Typography>
                                <Paper
                                  key={"1"}
                                  id={"ejYaE"}
                                  elevation={"{3}"}
                                  style={qdmstyles.Zuh}
                                >
                                  <Avatar
                                    key={"0"}
                                    id={"wg8M8"}
                                    alt={"Avatar"}
                                    variant={"rounded"}
                                    src={
                                      "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/325367543"
                                    }
                                    style={qdmstyles.KQg}
                                  ></Avatar>
                                </Paper>
                              </Grid>
                            </Grid>
                            <Grid
                              key={"1"}
                              id={"CIdwA"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"2"}
                              md={"2"}
                              sm={"2"}
                              xl={"2"}
                              spacing={""}
                              xs={"2"}
                              item={true}
                            >
                              <Typography
                                key={"0"}
                                id={"criteria_typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"Criteria"}
                                aliasName={"criteriaheading"}
                                style={qdmstyles.oXGn}
                              ></Typography>
                              <Typography
                                key={"1"}
                                id={"toDisplayTheValue_Typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"To display the value"}
                                aliasName={"toDisplayTheValueTypography"}
                                style={qdmstyles.dsNK}
                              ></Typography>
                            </Grid>
                            <Grid
                              key={"2"}
                              id={"CIdwA"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={1}
                              md={1}
                              sm={1}
                              xl={1}
                              xs={1}
                            >
                              <Typography
                                key={"0"}
                                id={"defaultDispenseDuration&Uom_Typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"Frequency"}
                                aliasName={
                                  "defaultDispenseDuration&Uomtypography"
                                }
                                style={qdmstyles.mGkLH}
                              ></Typography>
                              <Typography
                                key={"1"}
                                id={"TodisplayTheValue_Typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"TID - TWICE DAILY"}
                                aliasName={"TodisplayTheValueTypography"}
                                style={qdmstyles.ODUkA}
                              ></Typography>
                            </Grid>
                            <Grid
                              key={"3"}
                              id={"CIdwA"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"2"}
                              md={"2"}
                              sm={"2"}
                              xl={"2"}
                              xs={"2"}
                            >
                              <Typography
                                key={"0"}
                                id={"maxdispdurationval&Uom_Typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"Duration Code & Uom"}
                                aliasName={"maxdispdurationval&UomTypography"}
                                style={qdmstyles.gtKUe}
                              ></Typography>
                              <Typography
                                key={"1"}
                                id={"toDisplayTheValue_Typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"02 DAYS"}
                                aliasName={"toDisplayTheValueTypography"}
                                style={qdmstyles.ENjS}
                              ></Typography>
                            </Grid>
                            <Grid
                              key={"4"}
                              id={"CIdwA"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"2"}
                              md={"2"}
                              sm={"2"}
                              xl={"2"}
                              xs={"2"}
                            >
                              <Typography
                                key={"0"}
                                id={"action_Typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"Dose Value & Uom"}
                                aliasName={"actionTypography"}
                                style={qdmstyles.uHMj}
                              ></Typography>
                              <Typography
                                key={"1"}
                                id={"gAydS"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"50 MG"}
                                aliasName={"stop"}
                                style={qdmstyles.SBw}
                              ></Typography>
                            </Grid>
                            <Grid
                              key={"5"}
                              id={"CIdwA"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"2"}
                              md={"2"}
                              sm={"2"}
                              xl={"2"}
                              xs={"2"}
                            >
                              <Typography
                                key={"0"}
                                id={"actionMessage_Id"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"Infusion Rate & Uom"}
                                aliasName={"actionMessageId"}
                                style={qdmstyles.iEX}
                              ></Typography>
                              <Typography
                                key={"1"}
                                id={"toDisplayTheValue_Typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"5 ML"}
                                aliasName={"toDisplayTheValueTypography"}
                                style={qdmstyles.piHGG}
                              ></Typography>
                            </Grid>
                            <Grid
                              key={"6"}
                              id={"CIdwA"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              lg={"2"}
                              md={"2"}
                              sm={"2"}
                              xl={"2"}
                              xs={"2"}
                            >
                              <Typography
                                key={"0"}
                                id={"actionMessage_Id"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"Infuse Over Duration & Uom"}
                                aliasName={"actionMessageId"}
                                style={qdmstyles.UiPDr}
                              ></Typography>
                              <Typography
                                key={"1"}
                                id={"toDisplayTheValue_Typography"}
                                align={"inherit"}
                                color={"initial"}
                                display={"initial"}
                                variant={"body1"}
                                children={"5 ML"}
                                aliasName={"toDisplayTheValueTypography"}
                                style={qdmstyles.LdK}
                              ></Typography>
                            </Grid>
                          </Grid>
                          <Grid
                            key={"1"}
                            id={"vLpha"}
                            container={true}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            item={true}
                            lg={1}
                            md={1}
                            sm={1}
                            xl={1}
                            xs={1}
                          >
                            <Grid
                              key={"0"}
                              id={"drg92"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              item={true}
                              lg={"6"}
                              md={"6"}
                              sm={"6"}
                              xl={"6"}
                              xs={"6"}
                            >
                              <Avatar
                                key={"0"}
                                id={"ZCDUZ"}
                                alt={"Avatar"}
                                variant={"rounded"}
                                src={
                                  "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317181412"
                                }
                                style={qdmstyles.xywW}
                              ></Avatar>
                            </Grid>
                            <Grid
                              key={"1"}
                              id={"w7zVn"}
                              container={""}
                              direction={"row"}
                              justifyContent={"center"}
                              alignItems={"center"}
                              item={true}
                              lg={"6"}
                              md={"6"}
                              sm={"6"}
                              xl={"6"}
                              xs={"6"}
                            >
                              <Avatar
                                key={"0"}
                                id={"SzaNP"}
                                alt={"Avatar"}
                                variant={"rounded"}
                                src={
                                  "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317182133"
                                }
                                style={qdmstyles.bCnu}
                              ></Avatar>
                            </Grid>
                          </Grid>
                        </Grid>
                      </Paper>
                    </Grid>
                  </Grid>
                </Paper>
              </Grid>
            </Grid>
          </Grid>
        </React.Fragment>
      )}
    </NamespacesConsumer>
  );
}

export default withRouter(translate()(Orderdetailscomp));
