import React from "react";
import { actions } from "drugmaster_v_dbinder";
import { NamespacesConsumer, translate } from "react-i18next";
import { withRouter } from "react-router-dom";
import { languageOptions, Permissions } from "../../utils";
import { LoggerContext } from "../../contexts";
import IDMPANEL from "idmpanel-pkg";
import { useDispatch, useSelector } from "react-redux";
import Config from "../../config";
import * as ALLMCORE from "@material-ui/core";
import cookie from "react-cookies";

import * as ALL from "../../components";
import { Modal } from "qdm-component-library";
import {
  Grid,
  Paper,
  Typography,
  Button,
  Box,
  Divider,
  TextField,
  Avatar,
} from "@material-ui/core";

import { Autocomplete } from "@material-ui/lab";
import qdmstyles from "./styles.json";
import "./index.css";
var aes256 = require("aes256");

function Despensedefaultcomp(props) {
  const dispatch = useDispatch();

  const contextType = React.useContext(LoggerContext);
  const [state, setState] = React.useState({
    permissionData: null,
  });

  const changeState = (key, value) => {
    setState({
      ...state,
      [key]: value,
    });
  };

  React.useEffect(() => {
    /// initializing transalation
    if (sessionStorage.defaultLng) {
      const { i18n } = props;
      i18n.changeLanguage(sessionStorage.defaultLng);
    }
    /// setlogger && dispatch of all events

    /// fetch all permission
  }, []);

  ///fetching all permission

  React.useEffect(() => {}, [state]);

  const { data, index } = props;

  return (
    <NamespacesConsumer>
      {(t, { i18n }) => (
        <React.Fragment>
          <Grid
            key={"0"}
            id={"bfymE"}
            container={""}
            direction={"row"}
            justifyContent={"center"}
            alignItems={"center"}
          >
            <Paper
              key={"0"}
              id={"paper_coverforaddnew"}
              elevation={"{3}"}
              aliasName={"papercoverforaddnew"}
              style={qdmstyles.HyGnC}
            >
              <Grid
                key={"0"}
                id={"b7AAp"}
                container={""}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
              >
                <Grid
                  key={"0"}
                  id={"pULoO"}
                  container={true}
                  direction={"row"}
                  justifyContent={"space-between"}
                  alignItems={"flex-start"}
                  lg={"auto"}
                  item={true}
                  alignContent={"stretch"}
                  md={"auto"}
                  sm={"auto"}
                  xl={"auto"}
                  xs={"auto"}
                  style={qdmstyles.hJTj}
                >
                  <Typography
                    key={"0"}
                    id={"addNewDispensedefaultheading"}
                    align={"inherit"}
                    color={"primary"}
                    display={"initial"}
                    variant={"body1"}
                    children={"ADD NEW DISPENSE DEFAULTS"}
                    aliasName={"addNewDispensedefaultheading"}
                    style={qdmstyles.JfSS}
                  ></Typography>
                  <Typography
                    key={"1"}
                    id={"addNewDispensedefaultheading"}
                    align={"inherit"}
                    color={"primary"}
                    display={"initial"}
                    variant={"body1"}
                    children={"cancel"}
                    aliasName={"addNewDispensedefaultheading"}
                    style={qdmstyles.FIySA}
                  ></Typography>
                </Grid>
              </Grid>
              <Grid
                key={"1"}
                id={"0NqD2"}
                container={""}
                direction={"row"}
                justifyContent={"flex-start"}
                alignItems={"center"}
                item={true}
                lg={"12"}
                style={qdmstyles.KWgvx}
              >
                <Paper
                  key={"0"}
                  id={"A4OWh"}
                  elevation={""}
                  variant={"elevation"}
                  style={qdmstyles.FDGI}
                >
                  <Grid
                    key={"0"}
                    id={"0wzSg"}
                    container={""}
                    direction={"row"}
                    justifyContent={"flex-start"}
                    alignItems={"center"}
                    style={qdmstyles.suz}
                  >
                    <Typography
                      key={"0"}
                      id={"defineCriteriaByPatientAndPharmacy_heading"}
                      align={"inherit"}
                      color={"primary"}
                      display={"initial"}
                      variant={"body1"}
                      children={"DEFINE CRITERIA BY PATIENT AND PHARMACY"}
                      aliasName={"defineCriteriaByPatientAndPharmacytypography"}
                      style={qdmstyles.xOuU}
                    ></Typography>
                    <Grid
                      key={"1"}
                      id={"Ew1Xu"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"12"}
                      style={qdmstyles.uhnDj}
                    >
                      <Paper
                        key={"0"}
                        id={"Sx8CG"}
                        elevation={"{3}"}
                        style={qdmstyles.arabZ}
                      >
                        <Grid
                          key={"0"}
                          id={"h6VuZ"}
                          container={true}
                          direction={"row"}
                          justifyContent={"flex-start"}
                          alignItems={"center"}
                          lg={"12"}
                          item={""}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                        >
                          <Grid
                            key={"0"}
                            id={"wDQNk"}
                            container={""}
                            direction={"row"}
                            justifyContent={"flex-start"}
                            alignItems={"center"}
                            item={true}
                            lg={"auto"}
                            style={qdmstyles.MYHwo}
                          >
                            <Button
                              key={"0"}
                              id={"addNewRuleSet_Button"}
                              variant={"text"}
                              color={"primary"}
                              children={"Add New Rule Set"}
                              aliasName={"addNewRuleSetButton"}
                              style={qdmstyles.FoTd}
                            ></Button>
                          </Grid>
                          <Grid
                            key={"1"}
                            id={"CU1k8"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                          >
                            <Typography
                              key={"0"}
                              id={"(or)_header"}
                              align={"inherit"}
                              color={"initial"}
                              display={"initial"}
                              variant={"body1"}
                              children={"(or)"}
                              aliasName={"(or)header"}
                            ></Typography>
                          </Grid>
                          <Grid
                            key={"2"}
                            id={"DWbgk"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            item={true}
                            lg={"auto"}
                            style={qdmstyles.qrjcz}
                          >
                            <Button
                              key={"0"}
                              id={"addExistingRuleSet_button"}
                              variant={"text"}
                              color={"primary"}
                              children={"Add Existing Rule Set"}
                              aliasName={"addExistingRuleSetbutton"}
                              style={qdmstyles.SVdEr}
                            ></Button>
                          </Grid>
                        </Grid>
                      </Paper>
                    </Grid>
                    <Grid
                      key={"2"}
                      id={"9w7mS"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                    >
                      <Box
                        key={"0"}
                        id={"Zq4Lx"}
                        m={1}
                        component={"div"}
                        style={qdmstyles.zIaSk}
                      >
                        <Divider
                          key={"0"}
                          id={"divider_adddispensedefault"}
                          variant={"fullWidth"}
                          orientation={"horizontal"}
                          light={""}
                          flexItem={""}
                          absolute={""}
                          aliasName={"dividerofadddispensedefault"}
                        ></Divider>
                      </Box>
                    </Grid>
                    <Grid
                      key={"3"}
                      id={"qsdJf"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      item={true}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      spacing={"2"}
                      style={qdmstyles.DVD}
                    >
                      <Grid
                        key={"0"}
                        id={"2MXs9"}
                        container={true}
                        direction={"column"}
                        justifyContent={"center"}
                        alignItems={"flex-start"}
                        item={true}
                        lg={"3"}
                        md={"6"}
                        sm={"6"}
                        xl={"3"}
                        xs={"6"}
                        alignContent={"center"}
                      >
                        <Grid
                          key={"0"}
                          id={"d2nWC"}
                          container={""}
                          direction={"column"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"12"}
                          xs={"12"}
                          xl={"12"}
                          sm={"12"}
                          md={"12"}
                        >
                          <Typography
                            key={"0"}
                            id={"defaultDispenseDuration&Uom_heading"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Default Dispense Duration & Uom"}
                            aliasName={"defaultDispenseDuration&Uom"}
                            style={qdmstyles.wpXAq}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"1"}
                          id={"d2nWC"}
                          container={true}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                          style={qdmstyles.WPTV}
                        >
                          <Grid
                            key={"0"}
                            id={"d2nWC"}
                            container={true}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            item={true}
                            lg={"6"}
                            md={"6"}
                            sm={"6"}
                            xl={"6"}
                            xs={"6"}
                          >
                            <TextField
                              key={"0"}
                              id={"defaultDispenseDuration&Uominput"}
                              label={""}
                              placeholder={""}
                              type={"text"}
                              select={""}
                              size={"small"}
                              variant={"outlined"}
                              fullWidth={true}
                              margin={"none"}
                              aliasName={"defaultDispenseDuration&UomTextfield"}
                              style={qdmstyles.bHKYo}
                            ></TextField>
                          </Grid>
                          <Grid
                            key={"1"}
                            id={"d2nWC"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            item={true}
                            lg={"6"}
                            xs={"6"}
                            xl={"6"}
                            sm={"6"}
                            md={"6"}
                          >
                            <Autocomplete
                              id={"Lxtmr"}
                              style={qdmstyles?.Lxtmr}
                              value={state?.despensedefaultcomp_lxtmr ?? null}
                              onLoad={() =>
                                setState({
                                  despensedefaultcomp_lxtmr:
                                    state?.despensedefaultcomp_lxtmr ?? null,
                                })
                              }
                              getOptionLabel={(option) => option?.["label"]}
                              options={[] ?? []}
                              size={"small"}
                              renderInput={(params) => (
                                <ALLMCORE.TextField
                                  {...params}
                                  label={"label"}
                                  variant="outlined"
                                />
                              )}
                            />
                          </Grid>
                        </Grid>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"2MXs9"}
                        container={true}
                        direction={"column"}
                        justifyContent={"flex-start"}
                        alignItems={"flex-start"}
                        item={true}
                        lg={"2"}
                        md={"6"}
                        sm={"6"}
                        xl={"2"}
                        xs={"6"}
                      >
                        <Grid
                          key={"0"}
                          id={"d2nWC"}
                          container={""}
                          direction={"column"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                        >
                          <Typography
                            key={"0"}
                            id={"maxdispdurationval&Uom_heading "}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Maxdispdurationval & Uom"}
                            aliasName={"maxdispdurationval&UomTypography "}
                            style={qdmstyles.VJX}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"1"}
                          id={"d2nWC"}
                          container={true}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                          style={qdmstyles.Exqmy}
                        >
                          <Grid
                            key={"0"}
                            id={"d2nWC"}
                            container={true}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            item={true}
                            lg={"6"}
                            md={"6"}
                            sm={"6"}
                            xl={"6"}
                            xs={"6"}
                          >
                            <TextField
                              key={"0"}
                              id={"maxdispdurationval&Uom_Textfield"}
                              label={""}
                              placeholder={""}
                              type={"text"}
                              select={""}
                              size={"small"}
                              variant={"outlined"}
                              fullWidth={true}
                              margin={"none"}
                              aliasName={"maxdispdurationval&Uominput"}
                              style={qdmstyles.cFu}
                            ></TextField>
                          </Grid>
                          <Grid
                            key={"1"}
                            id={"d2nWC"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            item={true}
                            lg={"6"}
                            xs={"6"}
                            xl={"6"}
                            sm={"6"}
                            md={"6"}
                          >
                            <Autocomplete
                              id={"OXRzD"}
                              style={qdmstyles?.OXRzD}
                              value={state?.despensedefaultcomp_oxrzd ?? null}
                              onLoad={() =>
                                setState({
                                  despensedefaultcomp_oxrzd:
                                    state?.despensedefaultcomp_oxrzd ?? null,
                                })
                              }
                              getOptionLabel={(option) => option?.["label"]}
                              options={[] ?? []}
                              size={"small"}
                              renderInput={(params) => (
                                <ALLMCORE.TextField
                                  {...params}
                                  label={"label"}
                                  variant="outlined"
                                />
                              )}
                            />
                          </Grid>
                        </Grid>
                      </Grid>
                      <Grid
                        key={"2"}
                        id={"2MXs9"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-start"}
                        alignItems={"center"}
                        item={true}
                        lg={"2"}
                        md={"3"}
                        sm={"3"}
                        xl={"2"}
                        xs={"3"}
                      >
                        <Grid
                          key={"0"}
                          id={"d2nWC"}
                          container={""}
                          direction={"column"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                        >
                          <Typography
                            key={"0"}
                            id={"action_heading"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Action"}
                            aliasName={"actionTypography"}
                            comment={""}
                            style={qdmstyles.onNLr}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"1"}
                          id={"d2nWC"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                        >
                          <Autocomplete
                            id={"d1D8Z"}
                            style={qdmstyles?.dDZ}
                            value={state?.despensedefaultcomp_d1d8z ?? null}
                            onLoad={() =>
                              setState({
                                despensedefaultcomp_d1d8z:
                                  state?.despensedefaultcomp_d1d8z ?? null,
                              })
                            }
                            getOptionLabel={(option) => option?.["label"]}
                            options={[] ?? []}
                            size={"small"}
                            renderInput={(params) => (
                              <ALLMCORE.TextField
                                {...params}
                                label={"label"}
                                variant="outlined"
                              />
                            )}
                          />
                        </Grid>
                      </Grid>
                      <Grid
                        key={"3"}
                        id={"2MXs9"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-start"}
                        alignItems={"center"}
                        item={true}
                        lg={"5"}
                        md={"9"}
                        sm={"9"}
                        xl={"5"}
                        xs={"9"}
                      >
                        <Grid
                          key={"0"}
                          id={"d2nWC"}
                          container={""}
                          direction={"column"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                        >
                          <Typography
                            key={"0"}
                            id={"actionMessage_heading"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Action Message"}
                            aliasName={"actionMessage_typography"}
                            style={qdmstyles.sXqXt}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"1"}
                          id={"d2nWC"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"12"}
                          md={"12"}
                          sm={"12"}
                          xl={"12"}
                          xs={"12"}
                        >
                          <TextField
                            key={"0"}
                            id={"actionmessage_input"}
                            label={""}
                            placeholder={"Type Here"}
                            type={"text"}
                            select={""}
                            size={"small"}
                            variant={"outlined"}
                            fullWidth={true}
                            margin={"none"}
                            aliasName={"actionmessageTextfield"}
                            style={qdmstyles.dcmVQ}
                          ></TextField>
                        </Grid>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"4"}
                      id={"iRF0G"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-end"}
                      alignItems={"center"}
                      item={true}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.vxru}
                    >
                      <Grid
                        key={"0"}
                        id={"Bf7YT"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-end"}
                        alignItems={"center"}
                        lg={"4"}
                        spacing={""}
                        md={"4"}
                        sm={"4"}
                        xl={"4"}
                        xs={"4"}
                        item={true}
                      >
                        <Button
                          key={"0"}
                          id={"save&AddAnother_Button"}
                          variant={"text"}
                          color={"primary"}
                          children={"Save & Add another"}
                          aliasName={"save&AddAnotherButton"}
                          style={qdmstyles.mbBtY}
                        ></Button>
                        <Grid
                          key={"1"}
                          id={""}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          style={qdmstyles.RkD}
                        >
                          <Button
                            key={"0"}
                            id={"addButtonofaddnewdispensedefault_Button"}
                            variant={"contained"}
                            color={"primary"}
                            children={" Add"}
                            size={"small"}
                            aliasName={"addButtonofaddnewdispensedefault"}
                            style={qdmstyles.iUJe}
                          ></Button>
                        </Grid>
                      </Grid>
                    </Grid>
                  </Grid>
                </Paper>
              </Grid>
              <Grid
                key={"2"}
                id={"uo50z"}
                container={true}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
              >
                <Grid
                  key={"0"}
                  id={"FP3C7"}
                  container={""}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"center"}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                >
                  <Paper
                    key={"0"}
                    id={"bHiFf"}
                    elevation={"{3}"}
                    style={qdmstyles.yIZX}
                  >
                    <Grid
                      key={"0"}
                      id={"GYTKC"}
                      container={true}
                      direction={"row"}
                      justifyContent={"space-between"}
                      alignItems={"center"}
                      lg={"12"}
                      item={true}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      wrap={"wrap"}
                    >
                      <Grid
                        key={"0"}
                        id={"fQkr3"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-start"}
                        alignItems={"center"}
                        lg={"10"}
                        md={true}
                        sm={true}
                        xl={true}
                        xs={true}
                        item={true}
                        spacing={1}
                        style={qdmstyles.zPeg}
                      >
                        <Grid
                          key={"0"}
                          id={"Ut94g"}
                          container={true}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={1}
                          md={1}
                          sm={1}
                          xl={1}
                          xs={1}
                          wrap={"wrap"}
                          style={qdmstyles.MljIi}
                        >
                          <Grid
                            key={"0"}
                            id={"Po8nM"}
                            container={""}
                            direction={"row"}
                            justifyContent={"center"}
                            alignItems={"center"}
                            lg={"12"}
                            item={true}
                            md={"6"}
                            sm={"6"}
                            xl={"6"}
                            xs={"6"}
                            wrap={"wrap"}
                            style={qdmstyles.bLKp}
                          >
                            <Typography
                              key={"0"}
                              id={"serialnoTypography"}
                              align={"inherit"}
                              color={"initial"}
                              display={"initial"}
                              variant={"body1"}
                              children={1}
                              noWrap={""}
                              aliasName={"serialnoTypography"}
                              style={qdmstyles.UNEs}
                            ></Typography>
                            <Paper
                              key={"1"}
                              id={"ejYaE"}
                              elevation={"{3}"}
                              style={qdmstyles.TeoI}
                            ></Paper>
                          </Grid>
                        </Grid>
                        <Grid
                          key={"1"}
                          id={"CIdwA"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"2"}
                          md={"2"}
                          sm={"2"}
                          xl={"2"}
                          spacing={""}
                          xs={"2"}
                          item={true}
                        >
                          <Typography
                            key={"0"}
                            id={"criteria_typography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Criteria"}
                            aliasName={"criteriaheading"}
                            style={qdmstyles.oRfM}
                          ></Typography>
                          <Typography
                            key={"1"}
                            id={"toDisplayTheValue_Typography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"To display the value"}
                            aliasName={"toDisplayTheValueTypography"}
                            style={qdmstyles.lffOs}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"2"}
                          id={"CIdwA"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"3"}
                          md={"3"}
                          sm={"3"}
                          xl={"3"}
                          xs={"3"}
                        >
                          <Typography
                            key={"0"}
                            id={"defaultDispenseDuration&Uom_Typography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Default Dispense Duration & Uom"}
                            aliasName={"defaultDispenseDuration&Uomtypography"}
                            style={qdmstyles.cSt}
                          ></Typography>
                          <Typography
                            key={"1"}
                            id={"TodisplayTheValue_Typography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"To display the value"}
                            aliasName={"TodisplayTheValueTypography"}
                            style={qdmstyles.uJSVf}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"3"}
                          id={"CIdwA"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"2"}
                          md={"2"}
                          sm={"2"}
                          xl={"2"}
                          xs={"2"}
                        >
                          <Typography
                            key={"0"}
                            id={"maxdispdurationval&Uom_Typography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Maxdispdurationval & Uom"}
                            aliasName={"maxdispdurationval&UomTypography"}
                            style={qdmstyles.LClTU}
                          ></Typography>
                          <Typography
                            key={"1"}
                            id={"toDisplayTheValue_Typography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"To display the value"}
                            aliasName={"toDisplayTheValueTypography"}
                            style={qdmstyles.XZnoM}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"4"}
                          id={"CIdwA"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={1}
                          md={1}
                          sm={1}
                          xl={1}
                          xs={1}
                        >
                          <Typography
                            key={"0"}
                            id={"action_Typography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Action"}
                            aliasName={"actionTypography"}
                            style={qdmstyles.XYol}
                          ></Typography>
                          <Typography
                            key={"1"}
                            id={"gAydS"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"STOP"}
                            aliasName={"stop"}
                            style={qdmstyles.riMNP}
                          ></Typography>
                        </Grid>
                        <Grid
                          key={"5"}
                          id={"CIdwA"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          lg={"3"}
                          md={"2"}
                          sm={"2"}
                          xl={"2"}
                          xs={"2"}
                        >
                          <Typography
                            key={"0"}
                            id={"actionMessage_Id"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Action Message"}
                            aliasName={"actionMessageId"}
                            style={qdmstyles.Lgc}
                          ></Typography>
                          <Typography
                            key={"1"}
                            id={"toDisplayTheValue_Typography"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Duration exceeds maximum allowed"}
                            aliasName={"toDisplayTheValueTypography"}
                            style={qdmstyles.ZtcAo}
                          ></Typography>
                        </Grid>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"vLpha"}
                        container={true}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        item={true}
                        lg={1}
                        md={1}
                        sm={1}
                        xl={1}
                        xs={1}
                      >
                        <Grid
                          key={"0"}
                          id={"drg92"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"6"}
                          md={"6"}
                          sm={"6"}
                          xl={"6"}
                          xs={"6"}
                        >
                          <Avatar
                            key={"0"}
                            id={"ZCDUZ"}
                            alt={"Avatar"}
                            variant={"rounded"}
                            src={
                              "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317181412"
                            }
                            style={qdmstyles.fyxt}
                          ></Avatar>
                        </Grid>
                        <Grid
                          key={"1"}
                          id={"w7zVn"}
                          container={""}
                          direction={"row"}
                          justifyContent={"center"}
                          alignItems={"center"}
                          item={true}
                          lg={"6"}
                          md={"6"}
                          sm={"6"}
                          xl={"6"}
                          xs={"6"}
                        >
                          <Avatar
                            key={"0"}
                            id={"SzaNP"}
                            alt={"Avatar"}
                            variant={"rounded"}
                            src={
                              "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317182133"
                            }
                            style={qdmstyles.ktnIN}
                          ></Avatar>
                        </Grid>
                      </Grid>
                    </Grid>
                  </Paper>
                </Grid>
              </Grid>
            </Paper>
          </Grid>
        </React.Fragment>
      )}
    </NamespacesConsumer>
  );
}

export default withRouter(translate()(Despensedefaultcomp));
