import React from "react";
import { actions } from "drugmaster_v_dbinder";
import { NamespacesConsumer, translate } from "react-i18next";
import { withRouter } from "react-router-dom";
import { languageOptions, Permissions } from "../../utils";
import { LoggerContext } from "../../contexts";
import IDMPANEL from "idmpanel-pkg";
import { useDispatch, useSelector } from "react-redux";
import Config from "../../config";
import * as ALLMCORE from "@material-ui/core";
import cookie from "react-cookies";
import Froala from "react-froala-wysiwyg";
import FroalaEditorView from "react-froala-wysiwyg/FroalaEditorView";
import CloseRoundedIcon from "@material-ui/icons/CloseRounded";
import * as ALL from "../../components";
// import "froala-editor/js/plugins/fullscreen.min.js"

// Require Editor CSS files.
import "froala-editor/css/froala_style.min.css";
import "froala-editor/css/froala_editor.pkgd.min.css";
import "froala-editor/css/third_party/embedly.min.css";
// import "froala-editor/css/plugins/fullscreen.min.css";

import {
  Paper,
  Grid,
  Typography,
  Button,
  Avatar,
  Divider,
  Link,
  Box,
  Modal,
} from "@material-ui/core";
import { Autocomplete } from "custom-material-ui-component";
import qdmstyles from "./styles.json";
import "./index.css";
import { makeStyles } from "@material-ui/core";
var aes256 = require("aes256");
const useStyles = makeStyles((theme) => ({
  modal: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "8px",
  },
  grid: {
    outline: 0,
  },
}));
function Instructioncomp(props) {
  const dispatch = useDispatch();
  const classes = useStyles();
  const contextType = React.useContext(LoggerContext);
  const [state, setState] = React.useState({
    permissionData: null,
    showInstructionModal: false,
  });

  const changeState = (key, value) => {
    setState({
      ...state,
      [key]: value,
    });
  };
  const handlemodalclose = () => {
    setState({ showInstructionModal: false });
  };
  React.useEffect(() => {
    /// initializing transalation
    if (sessionStorage.defaultLng) {
      const { i18n } = props;
      i18n.changeLanguage(sessionStorage.defaultLng);
    }
    /// setlogger && dispatch of all events

    /// fetch all permission
  }, []);

  ///fetching all permission

  React.useEffect(() => {}, [state]);

  const { data, index } = props;

  return (
    <NamespacesConsumer>
      {(t, { i18n }) => (
        <React.Fragment>
          <Paper
            key={"0"}
            id={"DlhyF"}
            elevation={"{3}"}
            style={qdmstyles.hoZb}
          >
            <Grid
              key={"0"}
              id={"TgstR"}
              container={true}
              direction={"row"}
              justifyContent={"space-between"}
              alignItems={"center"}
              lg={"auto"}
              item={true}
              style={qdmstyles.qkQU}
            >
              <Grid
                key={"0"}
                id={"TgstR"}
                container={""}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                item={true}
                lg={"6"}
                xs={"6"}
                xl={"6"}
                sm={"6"}
                md={"6"}
              >
                <Typography
                  key={"0"}
                  id={"instructions_header"}
                  align={"left"}
                  color={"initial"}
                  display={"initial"}
                  variant={"body1"}
                  children={"INSTRUCTIONS"}
                  aliasName={"instructionsheader"}
                  style={qdmstyles.MpX}
                ></Typography>
              </Grid>
              <Grid
                key={"1"}
                id={"TgstR"}
                container={""}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                item={true}
              >
                <Button
                  key={"0"}
                  id={"instruction_add_new_button"}
                  variant={"text"}
                  color={"primary"}
                  children={"+ Add New"}
                  aliasName={"instructionaddnewbutton"}
                  onClick={() => setState({ showInstructionModal: true })}
                  style={qdmstyles.gPw}
                ></Button>
              </Grid>
            </Grid>
            <Grid
              key={"1"}
              id={"6gUvB"}
              container={true}
              direction={"row"}
              justifyContent={"flex-start"}
              alignItems={"center"}
              item={true}
              lg={"12"}
              md={"12"}
              sm={"12"}
              xl={"12"}
              xs={"12"}
            >
              <Paper
                key={"0"}
                id={"1Cfv0"}
                elevation={"{3}"}
                style={qdmstyles.QFILH}
              >
                <Grid
                  key={"0"}
                  id={"6gUvB"}
                  container={true}
                  direction={"row"}
                  justifyContent={"space-between"}
                  alignItems={"center"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.OphvD}
                >
                  <Grid
                    key={"0"}
                    id={"gP71K"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"4"}
                    md={"4"}
                    sm={"4"}
                    xs={"4"}
                    xl={"4"}
                  >
                    <Typography
                      key={"0"}
                      id={"practitioner_instruction_header"}
                      align={"left"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"PRACTITIONER INSTRUCTIONS"}
                      aliasName={"practitionerinstructionheader"}
                      style={qdmstyles.HZdY}
                    ></Typography>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"gP71K"}
                    container={true}
                    direction={"row"}
                    justifyContent={"flex-end"}
                    alignItems={"center"}
                    item={true}
                    lg={"2"}
                    md={"2"}
                    sm={"2"}
                    xs={"2"}
                    xl={"2"}
                  >
                    <Grid
                      key={"0"}
                      id={"Edit_icon2"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"5"}
                      md={"5"}
                      sm={"5"}
                      xl={"5"}
                      xs={"5"}
                      aliasName={"editIcon1"}
                      style={qdmstyles.fzmVy}
                    >
                      <Avatar
                        key={"0"}
                        id={"instrucrtion_delete_icon"}
                        alt={"Avatar"}
                        variant={"rounded"}
                        src={
                          "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317182133"
                        }
                        aliasName={"instrucrtiondeleteicon"}
                        style={qdmstyles.AjejV}
                      ></Avatar>
                      <Avatar
                        key={"1"}
                        id={"instruction_edit_icon"}
                        alt={"Avatar"}
                        variant={"rounded"}
                        src={
                          "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317313214"
                        }
                        aliasName={"instructionediticon"}
                        style={qdmstyles.PHlU}
                      ></Avatar>
                    </Grid>
                  </Grid>
                </Grid>
                <Grid
                  key={"1"}
                  id={"3DIMg"}
                  container={true}
                  direction={"column"}
                  justifyContent={"flex-start"}
                  alignItems={"flex-start"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.jiamz}
                >
                  <Grid
                    key={"0"}
                    id={"roJ0A"}
                    container={true}
                    direction={"column"}
                    justifyContent={"flex-start"}
                    alignItems={"flex-start"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"kZfj1"}
                      container={true}
                      direction={"row"}
                      justifyContent={"space-between"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      item={true}
                    >
                      <Grid
                        key={"0"}
                        id={"kZfj1"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        style={qdmstyles.TMqMD}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Instruction Description"}
                          style={qdmstyles.Lqop}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"kZfj1"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"12"}
                        md={"12"}
                        sm={"12"}
                        xl={"12"}
                        xs={"12"}
                        item={true}
                        style={qdmstyles.srNfC}
                      >
                        <Divider
                          key={"0"}
                          id={"JxlSx"}
                          variant={"fullWidth"}
                          orientation={"horizontal"}
                          light={""}
                          flexItem={""}
                          absolute={""}
                        ></Divider>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"roJ0A"}
                      container={true}
                      direction={"column"}
                      justifyContent={"flex-start"}
                      alignItems={"flex-start"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.YQQt}
                    >
                      <Typography
                        key={"0"}
                        id={"cTAwT"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={
                          "1. Pellentesque Tincidunt Tristique Neque, Eget Venenatis Enim Gravida Quis. Fusce At Egestas Libero. Cras Convallis Egestas Ullamcorper."
                        }
                        gutterBottom={""}
                        style={qdmstyles.TFbkV}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"2"}
                      id={"pBxUS"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-start"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.JqSu}
                    >
                      <Typography
                        key={"0"}
                        id={"cTAwT"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={
                          "2. Suspendisse Sed Ultricies Nisl, Pharetra Rutrum Mauris. Vestibulum At Massa Dui."
                        }
                        gutterBottom={""}
                        style={qdmstyles.McRR}
                      ></Typography>
                    </Grid>
                  </Grid>
                </Grid>
                <Grid
                  key={"2"}
                  id={"3DIMg"}
                  container={true}
                  direction={"column"}
                  justifyContent={"flex-start"}
                  alignItems={"flex-start"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.JVES}
                >
                  <Grid
                    key={"0"}
                    id={"kZfj1"}
                    container={true}
                    direction={"row"}
                    justifyContent={"space-between"}
                    alignItems={"center"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    item={true}
                    style={qdmstyles.XZHC}
                  >
                    <Grid
                      key={"0"}
                      id={"kZfj1"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"5"}
                      md={"5"}
                      sm={"5"}
                      xl={"5"}
                      xs={"5"}
                    >
                      <Typography
                        key={"0"}
                        id={"cTAwT"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"Instruction Local Language"}
                        style={qdmstyles.pKjj}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"OWLPK"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-end"}
                      alignItems={"center"}
                      lg={"5"}
                      md={"5"}
                      sm={"5"}
                      xl={"5"}
                      xs={"5"}
                      style={qdmstyles.BkLXe}
                    >
                      {/* See Less */}
                      <Link
                        key={"0"}
                        id={"iTnbM"}
                        underline={"always"}
                        comment={"See Less"}
                        color={"primary"}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"See Less"}
                          style={qdmstyles.EVKo}
                        ></Typography>
                      </Link>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"kZfj1"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    item={true}
                    style={qdmstyles.tUPl}
                  >
                    <Divider
                      key={"0"}
                      id={"JxlSx"}
                      variant={"fullWidth"}
                      orientation={"horizontal"}
                      light={""}
                      flexItem={""}
                      absolute={""}
                    ></Divider>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"roJ0A"}
                    container={true}
                    direction={"column"}
                    justifyContent={"flex-start"}
                    alignItems={"flex-start"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"roJ0A"}
                      container={true}
                      direction={"column"}
                      justifyContent={"flex-start"}
                      alignItems={"flex-start"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.aHRsm}
                    >
                      <Typography
                        key={"0"}
                        id={"cTAwT"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"1. Fermentum Tristique"}
                        gutterBottom={""}
                        style={qdmstyles.JVGNw}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"JAGTO"}
                      container={true}
                      direction={"row"}
                      justifyContent={"space-between"}
                      alignItems={"center"}
                    >
                      <Typography
                        key={"0"}
                        id={"cTAwT"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"2. Quis Convallis"}
                        gutterBottom={""}
                        style={qdmstyles.rWvHQ}
                      ></Typography>
                      <Grid
                        key={"1"}
                        id={"OWLPK"}
                        container={true}
                        direction={"row"}
                        justifyContent={"flex-end"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        style={qdmstyles.tTsk}
                      >
                        {/* See Less */}
                        <Link
                          key={"0"}
                          id={"iTnbM"}
                          underline={"always"}
                          comment={"See Less"}
                          color={"primary"}
                        >
                          <Typography
                            key={"0"}
                            id={"cTAwT"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"See Less"}
                            style={qdmstyles.ejpY}
                          ></Typography>
                        </Link>
                      </Grid>
                    </Grid>
                  </Grid>
                </Grid>
              </Paper>
            </Grid>
            <Grid
              key={"2"}
              id={"6gUvB"}
              container={true}
              direction={"row"}
              justifyContent={"flex-start"}
              alignItems={"center"}
              item={true}
              lg={"12"}
              md={"12"}
              sm={"12"}
              xl={"12"}
              xs={"12"}
            >
              <Paper
                key={"0"}
                id={"1Cfv0"}
                elevation={"{3}"}
                style={qdmstyles.pjCG}
              >
                <Grid
                  key={"0"}
                  id={"6gUvB"}
                  container={true}
                  direction={"row"}
                  justifyContent={"space-between"}
                  alignItems={"center"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.hcECK}
                >
                  <Grid
                    key={"0"}
                    id={"gP71K"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    lg={"3"}
                    md={"3"}
                    sm={"3"}
                    xs={"3"}
                    xl={"3"}
                  >
                    <Typography
                      key={"0"}
                      id={"patient_instruction_header"}
                      align={"left"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"PATIENT INSTRUCTIONS"}
                      aliasName={"patientinstructionheader"}
                      style={qdmstyles.vHwi}
                    ></Typography>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"gP71K"}
                    container={true}
                    direction={"row"}
                    justifyContent={"flex-end"}
                    alignItems={"center"}
                    item={true}
                    lg={"2"}
                    md={"2"}
                    sm={"2"}
                    xs={"2"}
                    xl={"2"}
                  >
                    <Grid
                      key={"0"}
                      id={"gP71K"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-end"}
                      alignItems={"center"}
                      item={true}
                      lg={true}
                      md={true}
                      sm={1}
                      xs={1}
                      xl={1}
                    >
                      <Grid
                        key={"0"}
                        id={"editicon_2"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        item={true}
                        lg={"5"}
                        md={"3"}
                        sm={"3"}
                        xl={"3"}
                        xs={"3"}
                        aliasName={"editicon2"}
                        style={qdmstyles.DHu}
                      >
                        <Avatar
                          key={"0"}
                          id={"patient_instruction_delete_icon"}
                          alt={"Avatar"}
                          variant={"rounded"}
                          src={
                            "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317182133"
                          }
                          aliasName={"patientinstructiondeleteicon"}
                          style={qdmstyles.Poee}
                        ></Avatar>
                        <Avatar
                          key={"1"}
                          id={"patient_instruction_edit_icon"}
                          alt={"Avatar"}
                          variant={"rounded"}
                          src={
                            "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/317313214"
                          }
                          aliasName={"patientinstructionediticon"}
                          style={qdmstyles.fAKr}
                        ></Avatar>
                      </Grid>
                    </Grid>
                  </Grid>
                </Grid>
                <Grid
                  key={"1"}
                  id={"3DIMg"}
                  container={true}
                  direction={"column"}
                  justifyContent={"flex-start"}
                  alignItems={"flex-start"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.yjucE}
                >
                  <Grid
                    key={"0"}
                    id={"roJ0A"}
                    container={true}
                    direction={"column"}
                    justifyContent={"flex-start"}
                    alignItems={"flex-start"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"kZfj1"}
                      container={true}
                      direction={"row"}
                      justifyContent={"space-between"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      item={true}
                      style={qdmstyles.uNKYS}
                    >
                      <Grid
                        key={"0"}
                        id={"kZfj1"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Instruction Description"}
                          style={qdmstyles.HlU}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"kZfj1"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"12"}
                        md={"12"}
                        sm={"12"}
                        xl={"12"}
                        xs={"12"}
                        item={true}
                        style={qdmstyles.YIsXY}
                      >
                        <Divider
                          key={"0"}
                          id={"JxlSx"}
                          variant={"fullWidth"}
                          orientation={"horizontal"}
                          light={""}
                          flexItem={""}
                          absolute={""}
                        ></Divider>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"roJ0A"}
                      container={true}
                      direction={"column"}
                      justifyContent={"flex-start"}
                      alignItems={"flex-start"}
                      style={qdmstyles.Jyph}
                    >
                      <Typography
                        key={"0"}
                        id={"cTAwT"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={
                          "1. Pellentesque Tincidunt Tristique Neque, Eget Venenatis Enim Gravida Quis. Fusce At Egestas Libero. Cras Convallis Egestas Ullamcorper."
                        }
                        gutterBottom={""}
                        style={qdmstyles.Joauv}
                      ></Typography>
                    </Grid>
                  </Grid>
                </Grid>
                <Grid
                  key={"2"}
                  id={"3DIMg"}
                  container={true}
                  direction={"column"}
                  justifyContent={"flex-start"}
                  alignItems={"flex-start"}
                  item={true}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.pNze}
                >
                  <Grid
                    key={"0"}
                    id={"kZfj1"}
                    container={true}
                    direction={"row"}
                    justifyContent={"space-between"}
                    alignItems={"center"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    item={true}
                    style={qdmstyles.RvRH}
                  >
                    <Grid
                      key={"0"}
                      id={"kZfj1"}
                      container={""}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"5"}
                      md={"5"}
                      sm={"5"}
                      xl={"5"}
                      xs={"5"}
                    >
                      <Typography
                        key={"0"}
                        id={"cTAwT"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"Instruction Local Language"}
                        style={qdmstyles.lxUb}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"OWLPK"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-end"}
                      alignItems={"center"}
                      lg={"5"}
                      md={"5"}
                      sm={"5"}
                      xl={"5"}
                      xs={"5"}
                      style={qdmstyles.EZCxK}
                    >
                      {/* See Less */}
                      <Link
                        key={"0"}
                        id={"iTnbM"}
                        underline={"always"}
                        comment={"See Less"}
                        color={"primary"}
                      >
                        <Typography
                          key={"0"}
                          id={"cTAwT"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"See More"}
                          style={qdmstyles.nuTOp}
                        ></Typography>
                      </Link>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"kZfj1"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                    item={true}
                    style={qdmstyles.QUXDg}
                  >
                    <Divider
                      key={"0"}
                      id={"JxlSx"}
                      variant={"fullWidth"}
                      orientation={"horizontal"}
                      light={""}
                      flexItem={""}
                      absolute={""}
                    ></Divider>
                  </Grid>
                  <Grid
                      key={"1"}
                      id={"roJ0A"}
                      container={true}
                      direction={"column"}
                      justifyContent={"flex-start"}
                      alignItems={"flex-start"}
                      style={qdmstyles.Jyph}
                    >
                      <Typography
                        key={"0"}
                        id={"cTAwT"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={
                          "1. Fermentum Tristique ."
                        }
                        gutterBottom={""}
                        style={qdmstyles.Joauv}
                      ></Typography>
                    </Grid>
                </Grid>
              </Paper>
            </Grid>
          </Paper>
          <Modal open={state.showInstructionModal} className={classes.modal}>
            <Grid
              key={"0"}
              id={"G1q6Q"}
              container={true}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
              lg={"6"}
              md={"6"}
              sm={"6"}
              xl={"6"}
              xs={"6"}
              className={classes.grid}
            >
              <Paper
                key={"0"}
                id={"I2if7"}
                elevation={"{3}"}
                style={qdmstyles.arK}
              >
                <Grid
                  key={"0"}
                  id={"sJZsO"}
                  container={true}
                  direction={"row"}
                  justifyContent={"space-between"}
                  alignItems={"center"}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  style={qdmstyles.TQIrv}
                >
                  <Grid
                    key={"0"}
                    id={"6Ygnf"}
                    container={false}
                    direction={"row"}
                    justifyContent={"flex-start"}
                    alignItems={"center"}
                    lg={"3"}
                    md={"6"}
                    sm={"6"}
                    xl={"3"}
                    xs={"6"}
                    item={true}
                  >
                    <Typography
                      key={"0"}
                      id={"addInstructions_Typography"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"ADD INSTRUCTIONS"}
                      aliasName={"addInstructionsTypography"}
                      style={qdmstyles.huQWE}
                    ></Typography>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"ohqRw"}
                    container={false}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    lg={1}
                    md={2}
                    sm={2}
                    xl={1}
                    xs={2}
                    item={true}
                  >
                    <Paper
                      key={"0"}
                      id={"close_icon"}
                      alt={"Avatar"}
                      variant={"rounded"}
                      aliasName={"closeicon"}
                      elevation={false}
                      style={{
                        width: "26px",
                        height: "26px",
                        borderRadius: "50%",
                        backgroundColor: "#E5E8EE",
                        display: "grid",
                        cursor: "pointer",
                      }}
                      onClick={() => handlemodalclose()}
                    >
                      <CloseRoundedIcon
                        fontSize="small"
                        style={{ placeSelf: "center" }}
                      />
                    </Paper>
                  </Grid>
                </Grid>
                <Divider
                  key={"1"}
                  id={"hzN6n"}
                  variant={"fullWidth"}
                  style={qdmstyles.TwDvp}
                ></Divider>
                <Grid
                  key={"2"}
                  id={"IwptL"}
                  container={true}
                  direction={"column"}
                  justifyContent={"center"}
                  alignItems={"center"}
                >
                  <Grid
                    key={"0"}
                    id={"mraSZ"}
                    container={true}
                    direction={"column"}
                    justifyContent={"center"}
                    alignItems={"flex-start"}
                    item={true}
                    lg={"12"}
                    md={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"Rrg5g"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                      lg={"6"}
                      md={"6"}
                      sm={"6"}
                      xl={"6"}
                      xs={"6"}
                      style={qdmstyles.Rrgg}
                    >
                      <Typography
                        key={"0"}
                        id={"InstructionType_Typography"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"Instruction Type"}
                        aliasName={"InstructionTypeTypography"}
                        style={qdmstyles.VNCk}
                      ></Typography>
                      <Autocomplete
                        getOptionLabel={(option) => option?.[""]}
                        options={[] ?? []}
                        size={"small"}
                        renderInput={(params) => (
                          <ALLMCORE.TextField
                            {...params}
                            label={""}
                            variant="outlined"
                          />
                        )}
                      />
                    </Grid>
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"mraSZ"}
                    container={true}
                    direction={"column"}
                    justifyContent={"center"}
                    alignItems={"flex-start"}
                    item={true}
                    lg={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"HKwb7"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-start"}
                      alignItems={"center"}
                      item={true}
                      lg={"6"}
                      md={"6"}
                      sm={"6"}
                      xl={"6"}
                      xs={"6"}
                    >
                      <Typography
                        key={"0"}
                        id={"instructionDescription_Typography"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"Instruction Description"}
                        aliasName={"instructionDescriptionTypography"}
                        style={qdmstyles.JFpJ}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"05l1O"}
                      container={false}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      item={true}
                    >
                      <Box key={"0"} id={"FSxha"} m={1} component={"div"}>
                        <Froala
                          tag="textarea"
                          config={{
                            attribution: false,
                            placeholder: "Start typing...",
                            toolbarButtons: {
                              moreText: {
                                buttons: [
                                  "bold",
                                  "italic",
                                  "underline",
                                  "strikeThrough",
                                  "subscript",
                                  "superscript",
                                  "fontFamily",
                                  "fontSize",
                                  "textColor",
                                  "backgroundColor",
                                  "inlineClass",
                                  "inlineStyle",
                                  "clearFormatting",
                                ],
                              },
                              moreParagraph: {
                                buttons: [
                                  "alignLeft",
                                  "alignCenter",
                                  "formatOLSimple",
                                  "alignRight",
                                  "alignJustify",
                                  "formatOL",
                                  "formatUL",
                                  "paragraphFormat",
                                  "paragraphStyle",
                                  "lineHeight",
                                  "outdent",
                                  "indent",
                                  "quote",
                                ],
                              },
                              moreRich: {
                                buttons: [
                                  "insertLink",
                                  "insertImage",
                                  "insertVideo",
                                  "insertTable",
                                  "emoticons",
                                  "fontAwesome",
                                  "specialCharacters",
                                  "embedly",
                                  "insertFile",
                                  "insertHR",
                                ],
                              },
                              moreMisc: {
                                buttons: [
                                  "undo",
                                  "redo",
                                  "fullscreen",
                                  "print",
                                  "getPDF",
                                  "spellChecker",
                                  "selectAll",
                                  "html",
                                  "help",
                                ],
                                align: "right",
                                buttonsVisible: 2,
                              },
                            },
                            pluginsEnabled: [
                              "table",
                              "spell",
                              "quote",
                              "save",
                              "quickInsert",
                              "paragraphFormat",
                              "paragraphStyle",
                              "help",
                              "draggable",
                              "align",
                              "link",
                              "lists",
                              "file",
                              "image",
                              "emoticons",
                              "url",
                              "video",
                              "embedly",
                              "colors",
                              "entities",
                              "inlineClass",
                              "inlineStyle",
                              // 'codeBeautif '
                              // 'spellChecker',
                              "imageTUI",
                            ],
                          }}
                        />
                        <br />
                        <FroalaEditorView />
                      </Box>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"mraSZ"}
                    container={true}
                    direction={"column"}
                    justifyContent={"center"}
                    alignItems={"flex-start"}
                    item={true}
                    lg={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"HKwb7"}
                      container={true}
                      direction={"row"}
                      justifyContent={"flex-start"}
                      alignItems={"center"}
                      item={true}
                      lg={"6"}
                      md={"6"}
                      sm={"6"}
                      xl={"6"}
                      xs={"6"}
                    >
                      <Typography
                        key={"0"}
                        id={"instruction_local_language_header"}
                        align={"inherit"}
                        color={"initial"}
                        display={"initial"}
                        variant={"body1"}
                        children={"Instruction Local Language"}
                        aliasName={"instructionlocallanguageheader"}
                        style={qdmstyles.BGX}
                      ></Typography>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"U5DoF"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                    >
                      <Box key={"0"} id={"cMq76"} m={1} component={"div"}>
                        {/* <FroalaEditorView /> */}
                        <Froala
                          tag="textarea"
                          config={{
                            attribution: false,
                            placeholder: "Start typing...",
                            toolbarButtons: {
                              moreText: {
                                buttons: [
                                  "bold",
                                  "italic",
                                  "underline",
                                  "strikeThrough",
                                  "subscript",
                                  "superscript",
                                  "fontFamily",
                                  "fontSize",
                                  "textColor",
                                  "backgroundColor",
                                  "inlineClass",
                                  "inlineStyle",
                                  "clearFormatting",
                                ],
                              },
                              moreParagraph: {
                                buttons: [
                                  "alignLeft",
                                  "alignCenter",
                                  "formatOLSimple",
                                  "alignRight",
                                  "alignJustify",
                                  "formatOL",
                                  "formatUL",
                                  "paragraphFormat",
                                  "paragraphStyle",
                                  "lineHeight",
                                  "outdent",
                                  "indent",
                                  "quote",
                                ],
                              },
                              moreRich: {
                                buttons: [
                                  "insertLink",
                                  "insertImage",
                                  "insertVideo",
                                  "insertTable",
                                  "emoticons",
                                  "fontAwesome",
                                  "specialCharacters",
                                  "embedly",
                                  "insertFile",
                                  "insertHR",
                                ],
                              },
                              moreMisc: {
                                buttons: [
                                  "undo",
                                  "redo",
                                  "fullscreen",
                                  "print",
                                  "getPDF",
                                  "spellChecker",
                                  "selectAll",
                                  "html",
                                  "help",
                                ],
                                align: "right",
                                buttonsVisible: 2,
                              },
                            },
                            pluginsEnabled: [
                              "table",
                              "spell",
                              "quote",
                              "save",
                              "quickInsert",
                              "paragraphFormat",
                              "paragraphStyle",
                              "help",
                              "draggable",
                              "align",
                              "link",
                              "lists",
                              "file",
                              "image",
                              "emoticons",
                              "url",
                              "video",
                              "embedly",
                              "colors",
                              "entities",
                              "inlineClass",
                              "inlineStyle",
                              // 'codeBeautif '
                              // 'spellChecker',
                              "imageTUI",
                            ],
                          }}
                        />
                        <br />
                      </Box>
                    </Grid>
                  </Grid>
                </Grid>
                <Grid
                  key={"3"}
                  id={"66hWy"}
                  container={true}
                  direction={"row"}
                  justifyContent={"flex-end"}
                  alignItems={"center"}
                  lg={"12"}
                  md={"12"}
                  sm={"12"}
                  xl={"12"}
                  xs={"12"}
                  spacing={1}
                  style={qdmstyles.yWg}
                >
                  <Grid
                    key={"0"}
                    id={"Et6L0"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    item={true}
                    spacing={"6"}
                    lg={"6"}
                    md={"3"}
                    sm={"6"}
                    xl={"6"}
                    xs={"6"}
                    style={qdmstyles.hYHKP}
                  >
                    <Button
                      key={"0"}
                      id={"save&Addanother_Button"}
                      variant={"text"}
                      color={"primary"}
                      children={"Save & Add another"}
                      size={"small"}
                      aliasName={"save&AddanotherButton"}
                      style={qdmstyles.bUu}
                    ></Button>
                    <Button
                      key={"1"}
                      id={"addButtonOfAddInstructionDailog_button"}
                      variant={"contained"}
                      color={"primary"}
                      children={" Add"}
                      size={"small"}
                      aliasName={"addButtonOfAddInstructionDailog"}
                      style={qdmstyles.ad}
                    ></Button>
                  </Grid>
                </Grid>
              </Paper>
            </Grid>
          </Modal>
        </React.Fragment>
      )}
    </NamespacesConsumer>
  );
}

export default withRouter(translate()(Instructioncomp));
