import React from "react";
import { actions } from "drugmaster_v_dbinder";
import { connect } from "react-redux";
import { NamespacesConsumer, translate } from "react-i18next";
import { withRouter } from "react-router-dom";
import { languageOptions, Permissions } from "../../utils";
import { LoggerContext } from "../../contexts";

import IDMPANEL from "idmpanel-pkg";
import Config from "../../config";
import cookie from "react-cookies";

import * as ALL from "../../components";
import * as ALLMCORE from "@material-ui/core";

import { Modal } from "qdm-component-library";

import {
  Grid,
  Paper,
  Typography,
  Box,
  Avatar,
  Switch,
  Divider,
  TextField,
} from "@material-ui/core";
import { ComponentRender } from "custom-material-ui-component";

import { Autocomplete } from "@material-ui/lab";

import qdmstyles from "./styles.json";
import "./index.css";
var aes256 = require("aes256");

class Samplescreen extends React.Component {
  static contextType = LoggerContext;
  constructor(props, context) {
    super(props, context);
    this.state = {
      permissionData: null,
    };
  }

  changeState = (key, value) => {
    this.setState({
      [key]: value,
    });
  };

  componentDidMount() {
    /// initializing transalation
    if (sessionStorage.defaultLng) {
      const { i18n } = this.props;
      i18n.changeLanguage(sessionStorage.defaultLng);
    }

    /// setlogger && dispatch of all events

    /// fetch all permission
  }

  ///fetching all permission

  shouldComponentUpdate(props, state) {
    return true;
  }

  render() {
    return (
      <NamespacesConsumer>
        {(t, { i18n }) => (
          <React.Fragment>
            <Grid
              key={"0"}
              id={"I06HM"}
              container={true}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
              lg={"12"}
            >
              <Grid
                key={"0"}
                id={"xHezf"}
                container={""}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                lg={"12"}
              >
                <Paper
                  key={"0"}
                  id={"gbfHy"}
                  elevation={"{3}"}
                  style={qdmstyles.vHhhg}
                >
                  <Grid
                    key={"0"}
                    id={"qAc9p"}
                    container={true}
                    direction={"row"}
                    justifyContent={"space-between"}
                    alignItems={"center"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"HKmhv"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"9"}
                      md={"9"}
                      sm={"9"}
                      xl={"9"}
                      xs={"9"}
                      spacing={1}
                      style={qdmstyles.jmIHR}
                    >
                      <Grid
                        key={"0"}
                        id={"LHGC4"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"3"}
                        item={true}
                        md={"3"}
                        sm={"3"}
                        xl={"3"}
                        xs={"3"}
                      >
                        <Typography
                          key={"0"}
                          id={"code_and_description_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Code & Description"}
                          aliasName={"codeanddescriptionheader"}
                          style={qdmstyles.SZDv}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"MA8np"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        item={true}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                      >
                        <Box
                          key={"0"}
                          id={"6rqU6"}
                          m={1}
                          component={"div"}
                          style={qdmstyles.LjTgr}
                        >
                          <Typography
                            key={"0"}
                            id={"class_header"}
                            align={"inherit"}
                            color={"initial"}
                            display={"initial"}
                            variant={"body1"}
                            children={"Class"}
                            aliasName={"classheader"}
                            style={qdmstyles.kgfre}
                          ></Typography>
                          <Avatar
                            key={"1"}
                            id={"dvGGD"}
                            alt={"Avatar"}
                            variant={"rounded"}
                            src={
                              "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/323278938"
                            }
                            style={qdmstyles.EFoLU}
                          ></Avatar>
                        </Box>
                      </Grid>
                      <Grid
                        key={"2"}
                        id={"jhYjV"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        item={true}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                      >
                        <Typography
                          key={"0"}
                          id={"category_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Category"}
                          aliasName={"categoryheader"}
                          style={qdmstyles.OOJf}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"3"}
                        id={"Tz6TR"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={1}
                        item={true}
                        sm={1}
                        xl={1}
                        xs={1}
                        md={1}
                      >
                        <Typography
                          key={"0"}
                          id={"type_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Type"}
                          aliasName={"typeheader"}
                          style={qdmstyles.gYQ}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"4"}
                        id={"fW36i"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={1}
                        item={true}
                        md={1}
                        sm={1}
                        xl={1}
                        xs={1}
                      >
                        <Typography
                          key={"0"}
                          id={"form_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Form"}
                          aliasName={"formheader"}
                          style={qdmstyles.OSFx}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"5"}
                        id={"ecYCH"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={1}
                        item={true}
                        md={1}
                        sm={1}
                        xl={1}
                        xs={1}
                      >
                        <Typography
                          key={"0"}
                          id={"route_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Route"}
                          aliasName={"routeheader"}
                          style={qdmstyles.hRYn}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"6"}
                        id={"ev6i9"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        item={true}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                        style={qdmstyles.pPOc}
                      >
                        <Typography
                          key={"0"}
                          id={"strength_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Strength"}
                          aliasName={"strengthheader"}
                          style={qdmstyles.NNF}
                        ></Typography>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"hUUJ7"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"2"}
                      md={"2"}
                      sm={"2"}
                      xl={"2"}
                      xs={"2"}
                      spacing={1}
                    >
                      <Grid
                        key={"0"}
                        id={"BYd0H"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"6"}
                        item={true}
                        md={"6"}
                        sm={"6"}
                        xl={"6"}
                        xs={"6"}
                      >
                        <Typography
                          key={"0"}
                          id={"status_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Status"}
                          aliasName={"statusheader"}
                          style={qdmstyles.icdl}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"YZbST"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"6"}
                        item={true}
                        xl={"6"}
                        xs={"6"}
                        sm={"6"}
                        md={"6"}
                      >
                        <Typography
                          key={"0"}
                          id={"action_header"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Action"}
                          aliasName={"actionheader"}
                          style={qdmstyles.BUlCz}
                        ></Typography>
                      </Grid>
                    </Grid>
                  </Grid>
                </Paper>
              </Grid>
            </Grid>
            <Grid
              key={"1"}
              id={"I06HM"}
              container={true}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
              lg={"12"}
            >
              <Grid
                key={"0"}
                id={"xHezf"}
                container={""}
                direction={"row"}
                justifyContent={"center"}
                alignItems={"center"}
                lg={"12"}
              >
                <Paper
                  key={"0"}
                  id={"gbfHy"}
                  elevation={"{3}"}
                  style={qdmstyles.USaM}
                >
                  <Grid
                    key={"0"}
                    id={"qAc9p"}
                    container={true}
                    direction={"row"}
                    justifyContent={"space-between"}
                    alignItems={"center"}
                    lg={"12"}
                    md={"12"}
                    sm={"12"}
                    xl={"12"}
                    xs={"12"}
                  >
                    <Grid
                      key={"0"}
                      id={"HKmhv"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"9"}
                      md={"9"}
                      sm={"9"}
                      xl={"9"}
                      xs={"9"}
                      spacing={1}
                      style={qdmstyles.xMRJs}
                    >
                      <Grid
                        key={"0"}
                        id={"LHGC4"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"3"}
                        item={true}
                        md={"3"}
                        sm={"3"}
                        xl={"3"}
                        xs={"3"}
                      >
                        <Typography
                          key={"0"}
                          id={"code_and_description_value"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"ROUTGEN-001 & AAMOXl"}
                          aliasName={"codeanddescriptionvalue"}
                          noWrap={true}
                          style={qdmstyles.jFQId}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"MA8np"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        item={true}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                        wrap={"wrap"}
                        style={qdmstyles.idvO}
                      >
                        <Typography
                          key={"0"}
                          id={"class_value"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Cardiovascular"}
                          aliasName={"classvalue"}
                          style={qdmstyles.jneP}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"2"}
                        id={"jhYjV"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        item={true}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                      >
                        <Typography
                          key={"0"}
                          id={"category_value"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Regular"}
                          aliasName={"categoryvalue"}
                          style={qdmstyles.SQuMa}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"3"}
                        id={"Tz6TR"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={1}
                        item={true}
                        sm={1}
                        xl={1}
                        xs={1}
                        md={1}
                      >
                        <Typography
                          key={"0"}
                          id={"type_value"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Medicine"}
                          aliasName={"typevalue"}
                          style={qdmstyles.YJULD}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"4"}
                        id={"fW36i"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={1}
                        item={true}
                        md={1}
                        sm={1}
                        xl={1}
                        xs={1}
                      >
                        <Typography
                          key={"0"}
                          id={"form_value"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Tablet"}
                          aliasName={"formvalue"}
                          style={qdmstyles.ykB}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"5"}
                        id={"ecYCH"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={1}
                        item={true}
                        md={1}
                        sm={1}
                        xl={1}
                        xs={1}
                      >
                        <Typography
                          key={"0"}
                          id={"route_value"}
                          align={"inherit"}
                          color={"initial"}
                          display={"initial"}
                          variant={"body1"}
                          children={"Oral"}
                          aliasName={"routevalue"}
                          style={qdmstyles.iRtfM}
                        ></Typography>
                      </Grid>
                      <Grid
                        key={"6"}
                        id={"ev6i9"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"2"}
                        item={true}
                        md={"2"}
                        sm={"2"}
                        xl={"2"}
                        xs={"2"}
                        style={qdmstyles.TAdx}
                      >
                        <Avatar
                          key={"0"}
                          id={"strength_value_icon"}
                          alt={"Avatar"}
                          variant={"rounded"}
                          aliasName={"strengthvalueicon"}
                          src={
                            "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/323303442"
                          }
                          style={qdmstyles.Jsnsj}
                        ></Avatar>
                      </Grid>
                    </Grid>
                    <Grid
                      key={"1"}
                      id={"hUUJ7"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"2"}
                      md={"2"}
                      sm={"2"}
                      xl={"2"}
                      xs={"2"}
                      spacing={1}
                    >
                      <Grid
                        key={"0"}
                        id={"BYd0H"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"6"}
                        item={true}
                        md={"6"}
                        sm={"6"}
                        xl={"6"}
                        xs={"6"}
                        style={qdmstyles.YmYZh}
                      >
                        <Switch
                          key={"0"}
                          id={"status_value"}
                          checked={true}
                          color={"primary"}
                          name={"switch"}
                          aliasName={"statusvalue"}
                        ></Switch>
                      </Grid>
                      <Grid
                        key={"1"}
                        id={"YZbST"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"6"}
                        item={true}
                        xl={"6"}
                        xs={"6"}
                        sm={"6"}
                        md={"6"}
                        style={qdmstyles.WDfc}
                      >
                        <Avatar
                          key={"0"}
                          id={"action_value_icon"}
                          alt={"Avatar"}
                          variant={"rounded"}
                          aliasName={"actionvalueicon"}
                          src={
                            "https://fileupload.dev.ainqaplatform.in/ATP_Platform_DEV/323299686"
                          }
                          style={qdmstyles.zAgHX}
                        ></Avatar>
                      </Grid>
                    </Grid>
                  </Grid>
                  <Divider
                    key={"1"}
                    id={"jL9Jj"}
                    variant={"fullWidth"}
                  ></Divider>
                </Paper>
              </Grid>
            </Grid>
            <ComponentRender
              key={"2"}
              id={"Ww0dP"}
              component={
                <ALL.Aliasmapping
                  propsState={this.state}
                  setFun={(value) => {
                    this.changeState("Aliasmapping", value);
                  }}
                  stateName={"Aliasmapping"}
                  statevalue={this.state?.Aliasmapping}
                />
              }
            ></ComponentRender>
            <Grid
              key={"3"}
              id={"C2Q2C"}
              container={true}
              direction={"row"}
              justifyContent={"center"}
              alignItems={"center"}
              lg={"12"}
              md={"12"}
              sm={"12"}
              xl={"12"}
              xs={"12"}
            >
              <Grid
                key={"0"}
                id={"A0aTF"}
                container={""}
                direction={"row"}
                justifyContent={"flex-start"}
                alignItems={"center"}
                lg={"12"}
                md={"12"}
                sm={"12"}
                xl={"12"}
                xs={"12"}
              >
                <Grid
                  key={"0"}
                  id={"K8jKe"}
                  container={true}
                  direction={"row"}
                  justifyContent={"center"}
                  alignItems={"flex-start"}
                  lg={"10"}
                  spacing={"2"}
                  md={"10"}
                  sm={"10"}
                  xl={"10"}
                  xs={"10"}
                >
                  <Grid
                    key={"0"}
                    id={"MwW3q"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    lg={"4"}
                    item={true}
                    md={"6"}
                    sm={"6"}
                    xl={"4"}
                    xs={"6"}
                    style={qdmstyles.MwWq}
                  >
                    <Typography
                      key={"0"}
                      id={"TI1yl"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Frequency"}
                      style={qdmstyles.TIyl}
                    ></Typography>
                    <Autocomplete
                      id={"6WRlV"}
                      style={qdmstyles?.WRlV}
                      value={this.state?.samplescreen_6wrlv ?? null}
                      onLoad={() =>
                        this.setState({
                          samplescreen_6wrlv:
                            this.state?.samplescreen_6wrlv ?? null,
                        })
                      }
                      getOptionLabel={(option) => option?.["label"]}
                      options={[] ?? []}
                      renderInput={(params) => (
                        <ALLMCORE.TextField
                          {...params}
                          label={"label"}
                          variant="outlined"
                        />
                      )}
                    />
                  </Grid>
                  <Grid
                    key={"1"}
                    id={"XcWnj"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    lg={"2"}
                    item={true}
                    md={"3"}
                    sm={"3"}
                    xl={"2"}
                    xs={"3"}
                  >
                    <Typography
                      key={"0"}
                      id={"b6j0B"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Duration Code & Uom"}
                      style={qdmstyles.bjB}
                    ></Typography>
                    <Grid
                      key={"1"}
                      id={"mTFOI"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.Fztb}
                    >
                      <Grid
                        key={"0"}
                        id={"56Ktj"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        item={true}
                        style={qdmstyles.DZvJu}
                      >
                        <TextField
                          key={"0"}
                          id={"KOrzv"}
                          label={""}
                          placeholder={""}
                          type={"text"}
                          variant={"outlined"}
                          fullWidth={true}
                          margin={"dense"}
                        ></TextField>
                      </Grid>
                      <Divider
                        key={"1"}
                        id={"i68WA"}
                        variant={"fullWidth"}
                        flexItem={true}
                        orientation={"vertical"}
                        style={qdmstyles.AIZE}
                      ></Divider>
                      <Grid
                        key={"2"}
                        id={"VtLuv"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        item={true}
                      >
                        <Autocomplete
                          id={"GUjrT"}
                          style={qdmstyles?.GUjrT}
                          value={this.state?.samplescreen_gujrt ?? null}
                          onLoad={() =>
                            this.setState({
                              samplescreen_gujrt:
                                this.state?.samplescreen_gujrt ?? null,
                            })
                          }
                          getOptionLabel={(option) => option?.["label"]}
                          options={[] ?? []}
                          renderInput={(params) => (
                            <ALLMCORE.TextField
                              {...params}
                              label={"label"}
                              variant="outlined"
                            />
                          )}
                        />
                      </Grid>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"2"}
                    id={"XcWnj"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    lg={"2"}
                    item={true}
                    md={"3"}
                    sm={"3"}
                    xl={"2"}
                    xs={"3"}
                  >
                    <Typography
                      key={"0"}
                      id={"b6j0B"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Dose Value & Uom"}
                      style={qdmstyles.diPri}
                    ></Typography>
                    <Grid
                      key={"1"}
                      id={"mTFOI"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.RSKx}
                    >
                      <Grid
                        key={"0"}
                        id={"56Ktj"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        item={true}
                        style={qdmstyles.TeIS}
                      >
                        <TextField
                          key={"0"}
                          id={"KOrzv"}
                          label={""}
                          placeholder={""}
                          type={"text"}
                          variant={"outlined"}
                          fullWidth={true}
                          margin={"dense"}
                        ></TextField>
                      </Grid>
                      <Divider
                        key={"1"}
                        id={"i68WA"}
                        variant={"fullWidth"}
                        flexItem={true}
                        orientation={"vertical"}
                        style={qdmstyles.hGKY}
                      ></Divider>
                      <Grid
                        key={"2"}
                        id={"VtLuv"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        item={true}
                      >
                        <Autocomplete
                          id={"aa4dH"}
                          style={qdmstyles?.aadH}
                          value={this.state?.samplescreen_aa4dh ?? null}
                          onLoad={() =>
                            this.setState({
                              samplescreen_aa4dh:
                                this.state?.samplescreen_aa4dh ?? null,
                            })
                          }
                          getOptionLabel={(option) => option?.["label"]}
                          options={[] ?? []}
                          renderInput={(params) => (
                            <ALLMCORE.TextField
                              {...params}
                              label={"label"}
                              variant="outlined"
                            />
                          )}
                        />
                      </Grid>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"3"}
                    id={"XcWnj"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    lg={"2"}
                    item={true}
                    md={"3"}
                    sm={"6"}
                    xl={"2"}
                    xs={"6"}
                  >
                    <Typography
                      key={"0"}
                      id={"b6j0B"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Infusion Rate & Uom"}
                      style={qdmstyles.AIP}
                    ></Typography>
                    <Grid
                      key={"1"}
                      id={"mTFOI"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.tRw}
                    >
                      <Grid
                        key={"0"}
                        id={"56Ktj"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        item={true}
                        style={qdmstyles.NRSM}
                      >
                        <TextField
                          key={"0"}
                          id={"KOrzv"}
                          label={""}
                          placeholder={""}
                          type={"text"}
                          variant={"outlined"}
                          fullWidth={true}
                          margin={"dense"}
                        ></TextField>
                      </Grid>
                      <Divider
                        key={"1"}
                        id={"i68WA"}
                        variant={"fullWidth"}
                        flexItem={true}
                        orientation={"vertical"}
                        style={qdmstyles.qaqFc}
                      ></Divider>
                      <Grid
                        key={"2"}
                        id={"VtLuv"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        item={true}
                      >
                        <Autocomplete
                          id={"5rkY2"}
                          style={qdmstyles?.rkY}
                          value={this.state?.samplescreen_5rky2 ?? null}
                          onLoad={() =>
                            this.setState({
                              samplescreen_5rky2:
                                this.state?.samplescreen_5rky2 ?? null,
                            })
                          }
                          getOptionLabel={(option) => option?.["label"]}
                          options={[] ?? []}
                          renderInput={(params) => (
                            <ALLMCORE.TextField
                              {...params}
                              label={"label"}
                              variant="outlined"
                            />
                          )}
                        />
                      </Grid>
                    </Grid>
                  </Grid>
                  <Grid
                    key={"4"}
                    id={"XcWnj"}
                    container={""}
                    direction={"row"}
                    justifyContent={"center"}
                    alignItems={"center"}
                    lg={"2"}
                    item={true}
                    md={"3"}
                    sm={"6"}
                    xl={"2"}
                    xs={"6"}
                  >
                    <Typography
                      key={"0"}
                      id={"b6j0B"}
                      align={"inherit"}
                      color={"initial"}
                      display={"initial"}
                      variant={"body1"}
                      children={"Infuse Over Duration & Uom"}
                      style={qdmstyles.hdS}
                    ></Typography>
                    <Grid
                      key={"1"}
                      id={"mTFOI"}
                      container={true}
                      direction={"row"}
                      justifyContent={"center"}
                      alignItems={"center"}
                      lg={"12"}
                      md={"12"}
                      sm={"12"}
                      xl={"12"}
                      xs={"12"}
                      style={qdmstyles.EDs}
                    >
                      <Grid
                        key={"0"}
                        id={"56Ktj"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        item={true}
                        style={qdmstyles.KPnp}
                      >
                        <TextField
                          key={"0"}
                          id={"KOrzv"}
                          label={""}
                          placeholder={""}
                          type={"text"}
                          variant={"outlined"}
                          fullWidth={true}
                          margin={"dense"}
                        ></TextField>
                      </Grid>
                      <Divider
                        key={"1"}
                        id={"i68WA"}
                        variant={"fullWidth"}
                        flexItem={true}
                        orientation={"vertical"}
                        style={qdmstyles.CGUz}
                      ></Divider>
                      <Grid
                        key={"2"}
                        id={"VtLuv"}
                        container={""}
                        direction={"row"}
                        justifyContent={"center"}
                        alignItems={"center"}
                        lg={"5"}
                        md={"5"}
                        sm={"5"}
                        xl={"5"}
                        xs={"5"}
                        item={true}
                      >
                        <Autocomplete
                          id={"s4XkO"}
                          style={qdmstyles?.sXkO}
                          value={this.state?.samplescreen_s4xko ?? null}
                          onLoad={() =>
                            this.setState({
                              samplescreen_s4xko:
                                this.state?.samplescreen_s4xko ?? null,
                            })
                          }
                          getOptionLabel={(option) => option?.["label"]}
                          options={[] ?? []}
                          renderInput={(params) => (
                            <ALLMCORE.TextField
                              {...params}
                              label={"label"}
                              variant="outlined"
                            />
                          )}
                        />
                      </Grid>
                    </Grid>
                  </Grid>
                </Grid>
              </Grid>
            </Grid>
            <ComponentRender
              key={"4"}
              id={"wNS9o"}
              component={
                <ALL.Orderdefault
                  propsState={this.state}
                  setFun={(value) => {
                    this.changeState("Orderdefault", value);
                  }}
                  stateName={"Orderdefault"}
                  statevalue={this.state?.Orderdefault}
                />
              }
            ></ComponentRender>
          </React.Fragment>
        )}
      </NamespacesConsumer>
    );
  }
}
const mapStateToProps = (state) => ({});

export default connect(
  mapStateToProps,
  actions
)(withRouter(translate()(Samplescreen)));
